// MUI `sx` 翻译版 —— 蒸馏页样式集中定义（原 Tailwind 模块 distillPageStyles.ts 已废弃删除）。
// 设计约束：蒸馏页使用近黑配色（#18181a 等），因此所有颜色保持字面色值，
// 不映射到主程序靛蓝主题 token。可直接消费：
//   <Box sx={distillTokens.CHAT_CARD_CLASS} />
// 动态 helper 见文件底部，返回 SxProps<Theme>。
import type { SxProps, Theme } from '@mui/material/styles'

export const distillTokens = {
  // —— 区块卡片 / 标题 ——
  SECTION_CARD_CLASS: {
    display: 'flex',
    flexDirection: 'column',
    gap: '24px',
    borderRadius: '20px 20px 0 0',
    bgcolor: '#FFF',
    p: '18px',
    boxShadow: '0 -4px 16px 0 rgba(0,0,0,0.05)',
  },
  SECTION_CARD_TITLE_CLASS: {
    fontSize: '14px',
    fontWeight: 500,
    color: '#18181a',
  },
  RETURN_BUTTON_CLASS: {
    height: '32px',
    gap: '4px',
    borderRadius: '10px',
    border: '0.5px solid',
    borderColor: '#e3e7f1',
    bgcolor: '#fff',
    px: '20px',
    fontSize: '12px',
    fontWeight: 400,
    color: '#757f9c',
    cursor: 'pointer',
    textTransform: 'none',
    '&:hover': { borderColor: '#cbd3e6', bgcolor: '#fff', color: '#18181a' },
    '&:focus-visible': { borderColor: '#cbd3e6', boxShadow: 'none', outline: 'none' },
    '&[aria-expanded="true"]': { borderColor: '#cbd3e6', bgcolor: '#fff', color: '#18181a' },
    '&[data-state="open"]': { borderColor: '#cbd3e6', bgcolor: '#fff', color: '#18181a' },
  },
  PRIMARY_BUTTON_CLASS: {
    height: '32px',
    gap: '4px',
    borderRadius: '10px',
    bgcolor: '#18181a',
    px: '20px',
    fontSize: '12px',
    fontWeight: 400,
    color: '#fff',
    border: 0,
    cursor: 'pointer',
    textTransform: 'none',
    '&:hover': { bgcolor: '#303030' },
  },

  // —— 页面布局 ——
  PAGE_CLASS: {
    display: 'flex',
    height: '100%',
    minHeight: 0,
    flexDirection: 'column',
    overflow: 'hidden',
    boxSizing: 'border-box',
    px: '26px',
    pt: '10px',
    pb: '22px',
    '@media (max-width: 900px)': { px: '4px' },
  },
  ACTIONS_CLASS: {
    mt: '20px',
    mb: '16px',
    display: 'flex',
    flexShrink: 0,
    flexWrap: 'wrap',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: '16px',
  },
  WORKBENCH_CLASS: {
    display: 'grid',
    minHeight: 0,
    flex: 1,
    gridTemplateColumns: '1fr',
    gap: '20px',
    overflow: 'hidden',
    '@media (min-width: 1280px)': {
      gridTemplateColumns: 'minmax(320px,0.72fr) minmax(0,1.28fr)',
      alignItems: 'stretch',
    },
  },

  // —— 区块卡片（聊天 / 来源共用） ——
  CARD_CLASS: {
    display: 'flex',
    flexDirection: 'column',
    gap: '24px',
    borderRadius: '20px 20px 0 0',
    bgcolor: '#FFF',
    p: '18px',
    boxShadow: '0 -4px 16px 0 rgba(0,0,0,0.05)',
    minHeight: 0,
    minWidth: 0,
    overflow: 'hidden',
  },
  CARD_BODY_CLASS: {
    display: 'flex',
    minHeight: 0,
    flex: 1,
    flexDirection: 'column',
    overflow: 'hidden',
  },
  CARD_HEADER_CLASS: {
    display: 'flex',
    flexShrink: 0,
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '12px',
  },
  CARD_OUTLINE_BUTTON_CLASS: {
    height: '32px',
    gap: '4px',
    borderRadius: '10px',
    border: '0.5px solid',
    borderColor: '#e3e7f1',
    bgcolor: '#fff',
    px: '20px',
    fontSize: '12px',
    fontWeight: 400,
    color: '#757f9c',
    cursor: 'pointer',
    textTransform: 'none',
    '&:hover': { borderColor: '#cbd3e6', bgcolor: '#fff', color: '#18181a' },
    '&:focus-visible': { borderColor: '#cbd3e6', boxShadow: 'none', outline: 'none' },
    '&[aria-expanded="true"]': { borderColor: '#cbd3e6', bgcolor: '#fff', color: '#18181a' },
    '&[data-state="open"]': { borderColor: '#cbd3e6', bgcolor: '#fff', color: '#18181a' },
  },
  CHAT_CARD_CLASS: {
    display: 'flex',
    flexDirection: 'column',
    gap: '24px',
    borderRadius: '20px 20px 0 0',
    bgcolor: '#FFF',
    p: '18px',
    boxShadow: '0 -4px 16px 0 rgba(0,0,0,0.05)',
    minHeight: 0,
    minWidth: 0,
    overflow: 'hidden',
  },
  CHAT_CARD_BODY_CLASS: {
    display: 'flex',
    minHeight: 0,
    flex: 1,
    flexDirection: 'column',
    overflow: 'hidden',
  },
  CHAT_CARD_DRAGGING_CLASS: {
    boxShadow: '0 0 0 1px rgba(24,24,26,0.15)',
  },
  SOURCE_CARD_CLASS: {
    display: 'flex',
    flexDirection: 'column',
    gap: '24px',
    borderRadius: '20px 20px 0 0',
    bgcolor: '#FFF',
    p: '18px',
    boxShadow: '0 -4px 16px 0 rgba(0,0,0,0.05)',
    minHeight: 0,
    minWidth: 0,
    overflow: 'hidden',
  },

  // —— 聊天面板 ——
  CHAT_PANEL_CLASS: {
    position: 'relative',
    display: 'flex',
    height: '100%',
    minWidth: 0,
    flexDirection: 'column',
  },
  CHAT_UPLOAD_DROP_HINT_CLASS: {
    pointerEvents: 'none',
    position: 'absolute',
    inset: 0,
    zIndex: 2,
    display: 'grid',
    placeItems: 'center',
    borderRadius: '12px',
    border: '1px dashed',
    borderColor: '#d1d5db',
    bgcolor: 'rgba(255,255,255,0.88)',
    fontSize: '14px',
    fontWeight: 500,
    color: '#18181a',
    backdropFilter: 'blur(4px)',
  },
  CHAT_MESSAGES_CLASS: {
    minHeight: 0,
    minWidth: 0,
    flex: 1,
    overflow: 'auto',
    bgcolor: '#fbfcfd',
    px: '20px',
    py: '18px',
  },
  CHAT_COMPOSER_SHELL_CLASS: {
    flexShrink: 0,
    borderTop: '1px solid',
    borderColor: '#eceef1',
    pt: '16px',
  },
  CHAT_COMPOSER_CLASS: {
    display: 'grid',
    gap: '12px',
  },
  CHAT_TEXTAREA_CLASS: {
    height: '112px',
    minHeight: '96px',
    maxHeight: '160px',
    resize: 'none',
    overflowY: 'auto',
    fieldSizing: 'fixed',
    borderRadius: '10px',
    border: '0.5px solid',
    borderColor: '#e3e7f1',
    bgcolor: '#fafafa',
    px: '14px',
    py: '12px',
    fontSize: '13px',
    lineHeight: '1.65',
    color: '#18181a',
    boxShadow: 'none',
    '&::placeholder': { color: '#c0c6d4' },
    '&:focus-visible': { borderColor: '#18181a', boxShadow: 'none', outline: 'none' },
  },
  CHAT_ACTIONS_CLASS: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '10px',
  },
  CHAT_ACTIONS_GROUP_CLASS: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: '8px',
  },
  CHAT_ROW_BASE_CLASS: {
    mb: '16px',
    display: 'flex',
    minWidth: 0,
  },
  CHAT_ROW_USER_CLASS: {
    justifyContent: 'flex-end',
    mb: '30px',
  },
  CHAT_ROW_ASSISTANT_CLASS: {},
  CHAT_BUBBLE_BASE_CLASS: {
    position: 'relative',
    boxSizing: 'border-box',
    maxWidth: 'min(720px,92%)',
    minWidth: 0,
    borderRadius: '12px',
    border: '1px solid',
    borderColor: '#eceef1',
    bgcolor: '#fff',
    px: '14px',
    py: '12px',
    fontSize: '13px',
    lineHeight: '1.65',
    whiteSpace: 'pre-wrap',
    overflowWrap: 'anywhere',
    color: '#18181a',
  },
  CHAT_BUBBLE_ASSISTANT_CLASS: {
    borderColor: 'transparent',
    bgcolor: '#fff',
    boxShadow: 'none',
  },
  CHAT_BUBBLE_USER_CLASS: {
    maxWidth: 'min(620px,80%)',
    borderRadius: '16px',
    borderColor: 'transparent',
    bgcolor: '#f0eee9',
    boxShadow: 'none',
  },
  CHAT_BUBBLE_USER_HAS_ATTACHMENTS_CLASS: {
    display: 'grid',
    maxWidth: 'min(620px,74%)',
    justifyItems: 'end',
    gap: '8px',
    borderRadius: 0,
    border: 0,
    bgcolor: 'transparent',
    p: 0,
    boxShadow: 'none',
  },
  CHAT_BUBBLE_USER_EDITING_CLASS: {
    minWidth: 'min(360px,72vw)',
    maxWidth: '84%',
    borderRadius: '16px',
    borderColor: 'transparent',
    bgcolor: '#f0eee9',
    px: '14px',
    py: '12px',
  },
  CHAT_BUBBLE_USER_EDITING_ATTACHMENTS_CLASS: {
    minWidth: 'min(520px,100%)',
    maxWidth: 'min(620px,74%)',
    borderRadius: 0,
    border: 0,
    bgcolor: 'transparent',
    p: 0,
  },
  CHAT_CONTENT_CLASS: {
    minWidth: 0,
    maxWidth: '100%',
    whiteSpace: 'pre-wrap',
    overflowWrap: 'anywhere',
  },
  CHAT_CONTENT_USER_ATTACHMENTS_CLASS: {
    maxWidth: '100%',
    borderRadius: '18px',
    bgcolor: '#f0eee9',
    px: '15px',
    py: '13px',
  },
  CHAT_THINKING_BLOCK_CLASS: {
    mb: '10px',
    minWidth: 0,
    maxWidth: '100%',
  },
  CHAT_THINKING_BUTTON_CLASS: {
    display: 'inline-flex',
    cursor: 'pointer',
    alignItems: 'center',
    gap: '7px',
    border: 0,
    bgcolor: 'transparent',
    p: 0,
    fontSize: '13px',
    fontWeight: 600,
    lineHeight: '1.5',
    color: '#62625e',
    '&:hover': { color: '#18181a' },
  },
  CHAT_THINKING_DETAILS_CLASS: {
    mb: '4px',
    mt: '10px',
    boxSizing: 'border-box',
    display: 'grid',
    maxWidth: '100%',
    minWidth: 0,
    gap: '6px',
    borderRadius: '10px',
    border: '1px solid',
    borderColor: '#eceef1',
    bgcolor: '#fafafa',
    p: '10px 12px',
    fontSize: '12px',
    lineHeight: '1.55',
    color: '#858b9c',
  },
  CHAT_THINKING_DETAIL_CLASS: {
    position: 'relative',
    minWidth: 0,
    pl: '14px',
    overflowWrap: 'anywhere',
    '&::before': {
      position: 'absolute',
      left: 0,
      top: '0.72em',
      width: '5px',
      height: '5px',
      borderRadius: '9999px',
      bgcolor: '#d1d5db',
      content: '""',
    },
  },
  CHAT_ATTACHMENTS_CLASS: {
    mb: '8px',
    display: 'grid',
    gap: '7px',
  },
  CHAT_ATTACHMENTS_USER_CLASS: {
    mb: 0,
    justifyItems: 'end',
  },
  CHAT_ATTACHMENT_CLASS: {
    display: 'grid',
    minHeight: '46px',
    width: 'min(260px,100%)',
    gridTemplateColumns: '32px minmax(0,1fr)',
    alignItems: 'center',
    gap: '9px',
    borderRadius: '8px',
    border: '1px solid',
    borderColor: '#eceef1',
    bgcolor: '#fbfaf8',
    p: '7px 10px 7px 7px',
    color: '#18181a',
    boxShadow: '0 5px 14px rgba(45,39,30,0.035)',
  },
  CHAT_ATTACHMENT_USER_CLASS: {
    ml: 'auto',
    bgcolor: '#f8f7f3',
  },
  CHAT_ATTACHMENT_ICON_CLASS: {
    display: 'inline-flex',
    width: '32px',
    height: '32px',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '8px',
    bgcolor: '#ef4444',
    fontSize: '15px',
    color: '#fff',
  },
  CHAT_ATTACHMENT_MAIN_CLASS: {
    display: 'grid',
    minWidth: 0,
    gap: '1px',
  },
  CHAT_ATTACHMENT_NAME_CLASS: {
    minWidth: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    fontSize: '12px',
    fontWeight: 600,
    lineHeight: '1.35',
  },
  CHAT_ATTACHMENT_TYPE_CLASS: {
    fontSize: '11px',
    lineHeight: '1.2',
    color: '#858b9c',
  },
  CHAT_EDIT_PANEL_CLASS: {
    display: 'grid',
    gap: '10px',
  },
  CHAT_EDIT_PANEL_USER_ATTACHMENTS_CLASS: {
    width: 'min(520px,100%)',
    borderRadius: '16px',
    bgcolor: '#f0eee9',
    px: '14px',
    py: '12px',
  },
  CHAT_EDIT_TEXTAREA_CLASS: {
    minHeight: '34px',
    resize: 'none',
    border: 0,
    bgcolor: 'transparent',
    p: 0,
    fontSize: '16px',
    lineHeight: '1.65',
    color: '#18181a',
    boxShadow: 'none',
    '&:focus-visible': { boxShadow: 'none', outline: 'none' },
  },
  CHAT_EDIT_ACTIONS_CLASS: {
    display: 'flex',
    justifyContent: 'flex-end',
    gap: '7px',
  },
  CHAT_HOVER_ACTIONS_CLASS: {
    position: 'absolute',
    right: '10px',
    bottom: '-26px',
    display: 'inline-flex',
    alignItems: 'center',
    gap: '9px',
    color: '#858b9c',
    opacity: 0,
    transition: 'opacity 0.15s',
    '&[data-bubble-group]:hover &': { opacity: 1 },
    '&[data-bubble-group]:focus-within &': { opacity: 1 },
  },
  CHAT_TIME_CLASS: {
    fontSize: '12px',
    lineHeight: 'none',
    color: '#858b9c',
  },
  CHAT_HOVER_BUTTON_CLASS: {
    display: 'inline-flex',
    width: '17px',
    height: '17px',
    alignItems: 'center',
    justifyContent: 'center',
    border: 0,
    bgcolor: 'transparent',
    p: 0,
    color: '#858b9c',
    '&:hover': { color: '#18181a' },
    '&:disabled': { cursor: 'not-allowed', opacity: 0.45 },
  },
  CHAT_WARNING_CLASS: {
    mt: '12px',
    display: 'grid',
    gap: '6px',
    borderRadius: '8px',
    border: '1px solid',
    borderColor: '#fed7aa',
    bgcolor: '#fff7ed',
    p: '10px 12px',
    fontSize: '12px',
    lineHeight: '1.55',
    color: '#7c2d12',
  },
  CHAT_WARNING_TITLE_CLASS: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    fontWeight: 600,
    color: '#9a3412',
  },
  CHAT_WARNING_ITEM_CLASS: {
    position: 'relative',
    whiteSpace: 'normal',
    overflowWrap: 'anywhere',
    pl: '18px',
    '&::before': {
      position: 'absolute',
      left: '6px',
      top: '0.72em',
      width: '4px',
      height: '4px',
      borderRadius: '9999px',
      bgcolor: '#fb923c',
      content: '""',
    },
  },
  CHAT_CONFIRM_CLASS: {
    mt: '12px',
    display: 'flex',
    gap: '8px',
  },
  CHAT_DECISION_CLASS: {
    mt: '10px',
    fontSize: '12px',
    color: '#858b9c',
  },

  // —— 上传列表 ——
  UPLOAD_LIST_CLASS: {
    display: 'grid',
    maxHeight: 'min(168px,30vh)',
    gap: '8px',
    overflowY: 'auto',
    overscrollBehavior: 'contain',
    pr: '2px',
    scrollbarGutter: 'stable',
  },
  UPLOAD_ITEM_BASE_CLASS: {
    display: 'grid',
    minHeight: '34px',
    minWidth: 0,
    gridTemplateColumns: 'auto minmax(0,1fr) auto auto',
    alignItems: 'center',
    gap: '8px',
    borderRadius: '10px',
    border: '1px solid',
    borderColor: '#eceef1',
    bgcolor: '#fafafa',
    p: '6px 8px',
    fontSize: '12px',
    color: '#18181a',
  },
  UPLOAD_ITEM_ERROR_CLASS: {
    borderColor: '#fecaca',
    bgcolor: '#fef2f2',
    color: '#d20b0b',
  },
  UPLOAD_NAME_CLASS: {
    minWidth: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  UPLOAD_STATUS_CLASS: {
    maxWidth: '160px',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    color: '#858b9c',
  },

  // —— 工具建议 ——
  TOOL_SUGGESTIONS_CLASS: {
    mt: '12px',
    display: 'grid',
    width: '100%',
    minWidth: 0,
    maxWidth: '100%',
    gap: '8px',
  },
  TOOL_SUGGESTION_CLASS: {
    position: 'relative',
    boxSizing: 'border-box',
    maxWidth: '100%',
    minWidth: 0,
    borderRadius: '10px',
    border: '1px solid',
    borderColor: '#eceef1',
    bgcolor: '#fffdf9',
    px: '12px',
    py: '11px',
    boxShadow: '0 6px 16px rgba(45,39,30,0.026)',
  },
  TOOL_SUGGESTION_MAIN_CLASS: {
    minWidth: 0,
    maxWidth: '100%',
    pr: '118px',
  },
  TOOL_SUGGESTION_HEAD_CLASS: {
    mb: '4px',
    display: 'flex',
    minWidth: 0,
    alignItems: 'center',
    gap: '7px',
  },
  TOOL_SUGGESTION_TITLE_CLASS: {
    minWidth: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    fontSize: '13px',
    fontWeight: 600,
    color: '#18181a',
  },
  TOOL_SUGGESTION_DESC_CLASS: {
    minWidth: 0,
    fontSize: '12px',
    lineHeight: '1.55',
    overflowWrap: 'anywhere',
    color: '#858b9c',
  },
  TOOL_SUGGESTION_META_CLASS: {
    mt: '7px',
    display: 'flex',
    minWidth: 0,
    maxWidth: '100%',
    alignItems: 'center',
    gap: '6px',
    fontSize: '11px',
    color: '#858b9c',
  },
  TOOL_METHOD_CLASS: {
    minWidth: '44px',
    flexShrink: 0,
    borderRadius: '9999px',
    border: '1px solid',
    borderColor: '#eceef1',
    bgcolor: '#fff',
    px: '7px',
    py: '1px',
    textAlign: 'center',
    fontSize: '11px',
    fontWeight: 600,
    color: '#18181a',
  },
  TOOL_SUGGESTION_ACTIONS_CLASS: {
    position: 'absolute',
    right: '12px',
    top: '10px',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: '8px',
  },
  TOOL_ACTION_GROUP_CLASS: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '4px',
    borderRadius: '9999px',
    border: '1px solid',
    borderColor: 'rgba(226,218,205,0.9)',
    bgcolor: 'rgba(255,255,255,0.78)',
    p: '2px',
    boxShadow: 'inset 0 1px 0 rgba(255,255,255,0.9)',
  },
  TOOL_ACTION_GROUP_DETAIL_CLASS: {
    width: '32px',
    height: '32px',
  },
  TOOL_ACTION_BUTTON_CLASS: {
    width: '26px',
    height: '26px',
    minWidth: '26px',
    borderRadius: '9999px',
    p: 0,
    color: '#858b9c',
    '&:hover': { bgcolor: '#f3f1eb', color: '#18181a' },
  },
  TOOL_ACTION_CONFIRM_CLASS: {
    color: '#166534',
    '&:hover': { bgcolor: '#dcfce7', color: '#14532d' },
    '&:disabled': { color: 'rgba(22,101,52,0.32)' },
  },
  TOOL_ACTION_REJECT_CLASS: {
    color: '#991b1b',
    '&:hover': { bgcolor: '#fee2e2', color: '#7f1d1d' },
  },
  TOOL_STATUS_BADGE_BASE_CLASS: {
    display: 'inline-flex',
    flexShrink: 0,
    alignItems: 'center',
    borderRadius: '9999px',
    border: '1px solid',
    px: '7px',
    py: '1px',
    fontSize: '11px',
    fontWeight: 600,
    lineHeight: '1.45',
  },

  // —— 改写模型按钮 ——
  REWRITE_MODEL_BUTTON_CLASS: {
    display: 'inline-flex',
    height: '32px',
    maxWidth: '220px',
    minWidth: 0,
    alignItems: 'center',
    gap: '8px',
    borderRadius: '10px',
    border: '0.5px solid',
    borderColor: '#e3e7f1',
    bgcolor: '#fff',
    px: '12px',
    fontSize: '12px',
    fontWeight: 400,
    color: '#757f9c',
    cursor: 'pointer',
    textTransform: 'none',
    boxShadow: 'none',
    '& > span:first-child': { minWidth: 0, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' },
    '&:hover': { borderColor: '#cbd3e6', bgcolor: '#fff', color: '#18181a' },
    '&:focus-visible': { borderColor: '#cbd3e6', boxShadow: 'none', outline: 'none' },
    '&[aria-expanded="true"]': { borderColor: '#cbd3e6', bgcolor: '#fff', color: '#18181a' },
    '&[data-state="open"]': { borderColor: '#cbd3e6', bgcolor: '#fff', color: '#18181a' },
  },

  // —— 来源工具栏 + 编辑器 ——
  SOURCE_TOOLBAR_CLASS: {
    mb: '12px',
    display: 'flex',
    flexShrink: 0,
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: '8px',
    borderRadius: '10px',
    bgcolor: '#fafafa',
    p: '8px',
  },
  SOURCE_EMPTY_STATE_CLASS: {
    display: 'flex',
    minHeight: '240px',
    flex: 1,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '10px',
    borderRadius: '12px',
    border: '1px dashed',
    borderColor: '#e3e7f1',
    bgcolor: '#fbfcfd',
    px: '24px',
    py: '32px',
    textAlign: 'center',
  },
  SOURCE_EMPTY_TEXT_CLASS: {
    fontSize: '13px',
    lineHeight: '20px',
    color: '#858b9c',
  },
  SOURCE_MD_CLASS: {
    boxSizing: 'border-box',
    display: 'grid',
    minHeight: 0,
    minWidth: 0,
    width: '100%',
    maxWidth: '100%',
    flex: 1,
    alignContent: 'flex-start',
    gap: '14px',
    alignSelf: 'stretch',
    overflowX: 'hidden',
    overflowY: 'auto',
    overscrollBehavior: 'contain',
    scrollbarGutter: 'stable',
    pr: 'clamp(6px,1vw,14px)',
  },
  SOURCE_GROUP_TITLE_CLASS: {
    my: '2px -2px',
    fontSize: '13px',
    fontWeight: 600,
    color: '#18181a',
  },
  SOURCE_STEPS_CLASS: {
    display: 'grid',
    gap: '12px',
  },
  SOURCE_STEP_BLOCK_CLASS: {
    display: 'grid',
    gap: '10px',
  },
  SOURCE_SECTION_CLASS: {
    position: 'relative',
    boxSizing: 'border-box',
    width: '100%',
    cursor: 'pointer',
    borderRadius: '10px',
    border: '1px solid',
    borderColor: '#eceef1',
    bgcolor: '#fff',
    p: '16px',
    textAlign: 'left',
    userSelect: 'text',
    '&:hover': { borderColor: '#04756f', boxShadow: '0 8px 22px rgba(4,117,111,0.08)' },
    '&:focus-visible': { outline: '2px solid #18181a', outlineOffset: '2px' },
  },
  SOURCE_SECTION_ACTIVE_CLASS: {
    borderColor: '#04756f',
    bgcolor: '#f3fbf8',
    boxShadow: '0 8px 22px rgba(4,117,111,0.08)',
  },
  SOURCE_SECTION_CHANGED_CLASS: {
    borderColor: '#04756f',
    bgcolor: '#effaf6',
    boxShadow: '0 12px 30px rgba(4,117,111,0.12)',
    transitionProperty: 'background, border-color, box-shadow',
    transitionDuration: '450ms',
  },
  SOURCE_SECTION_DIRTY_CLASS: {
    bgcolor: '#fffdf8',
    boxShadow: 'inset 3px 0 0 #d8c7a4',
  },
  SOURCE_SECTION_UPDATING_CLASS: {
    animation: 'pulse 2s cubic-bezier(0.4,0,0.6,1) infinite',
  },
  SOURCE_RENDERED_CLASS: {
    display: 'grid',
    gap: '12px',
    fontSize: '13px',
    lineHeight: '1.7',
    color: '#18181a',
  },
  SOURCE_META_LIST_CLASS: {
    display: 'grid',
    gap: '7px',
  },
  SOURCE_STEP_HEADER_CLASS: {
    display: 'flex',
    minWidth: 0,
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: '12px',
    pr: '6px',
  },
  SOURCE_LINE_CLASS: {
    display: 'grid',
    minHeight: '1.7em',
    minWidth: 0,
    maxWidth: '100%',
    gridTemplateColumns: '132px minmax(0,1fr)',
    alignItems: 'flex-start',
    gap: '10px',
    '@media (max-width: 760px)': { gridTemplateColumns: '1fr' },
  },
  SOURCE_LINE_COLLAPSIBLE_CLASS: {
    '& .source-edit-field': { width: '100%' },
  },
  SOURCE_LINE_READONLY_CLASS: {},
  SOURCE_KEY_CLASS: {
    fontSize: '12px',
    fontWeight: 600,
    color: '#858b9c',
  },
  SOURCE_VALUE_CLASS: {
    minWidth: 0,
    width: '100%',
    maxWidth: '100%',
    whiteSpace: 'pre-wrap',
    color: '#18181a',
  },
  SOURCE_READONLY_VALUE_CLASS: {
    display: 'block',
  },
  SOURCE_JSON_INLINE_CLASS: {
    m: 0,
    maxWidth: '100%',
    borderRadius: '8px',
    border: '1px solid',
    borderColor: '#eceef1',
    bgcolor: 'rgba(248,246,239,0.72)',
    p: '8px 10px',
    whiteSpace: 'pre-wrap',
    overflowWrap: 'anywhere',
    color: '#18181a',
  },
  SOURCE_EDIT_FIELD_CLASS: {
    display: 'flex',
    minWidth: 0,
    width: '100%',
    maxWidth: '100%',
    alignItems: 'flex-start',
  },
  PILL_OUTLINE_BUTTON_BASE: {
    display: 'inline-flex',
    cursor: 'pointer',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '4px',
    borderRadius: '9999px',
    border: '0.5px solid',
    borderColor: '#e3e7f1',
    bgcolor: '#fff',
    fontSize: '12px',
    fontWeight: 400,
    lineHeight: 'none',
    color: '#858b9c',
    boxShadow: 'none',
    transition: 'background-color 0.15s',
    '&:hover': { borderColor: '#04756f', bgcolor: '#fff', color: '#18181a' },
    '&:focus-visible': { borderColor: '#04756f', boxShadow: 'none', outline: 'none', color: '#18181a' },
    '& .anticon': { display: 'inline-flex', flexShrink: 0, alignItems: 'center', justifyContent: 'center' },
    '& .anticon svg': { display: 'block' },
  },
  NODE_INSERT_ROW_CLASS: {
    display: 'flex',
    justifyContent: 'center',
  },
  NODE_INSERT_ROW_EDGE_CLASS: {
    my: '2px',
  },
  PILL_OUTLINE_BUTTON_CLASS: {
    display: 'inline-flex',
    cursor: 'pointer',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '4px',
    height: '28px',
    borderRadius: '9999px',
    border: '0.5px solid',
    borderColor: '#e3e7f1',
    bgcolor: '#fff',
    px: '12px',
    fontSize: '12px',
    fontWeight: 400,
    lineHeight: 'none',
    color: '#858b9c',
    boxShadow: 'none',
    transition: 'background-color 0.15s',
    '&:hover': { borderColor: '#04756f', bgcolor: '#fff', color: '#18181a' },
    '&:focus-visible': { borderColor: '#04756f', boxShadow: 'none', outline: 'none', color: '#18181a' },
  },
  PILL_OUTLINE_BUTTON_SM_CLASS: {
    display: 'inline-flex',
    cursor: 'pointer',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '4px',
    height: '24px',
    borderRadius: '9999px',
    border: '0.5px solid',
    borderColor: '#e3e7f1',
    bgcolor: '#fff',
    px: '8px',
    fontSize: '12px',
    fontWeight: 400,
    lineHeight: 'none',
    color: '#858b9c',
    boxShadow: 'none',
    transition: 'background-color 0.15s',
    '&:hover': { borderColor: '#04756f', bgcolor: '#fff', color: '#18181a' },
    '&:focus-visible': { borderColor: '#04756f', boxShadow: 'none', outline: 'none', color: '#18181a' },
  },
  NODE_INSERT_BUTTON_CLASS: {
    display: 'inline-flex',
    cursor: 'pointer',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '4px',
    height: '28px',
    borderRadius: '9999px',
    border: '0.5px solid',
    borderColor: '#e3e7f1',
    bgcolor: '#fff',
    px: '12px',
    fontSize: '12px',
    fontWeight: 400,
    lineHeight: 'none',
    color: '#858b9c',
    boxShadow: 'none',
    transition: 'background-color 0.15s',
    '&:hover': { borderColor: '#04756f', bgcolor: '#fff', color: '#18181a' },
    '&:focus-visible': { borderColor: '#04756f', boxShadow: 'none', outline: 'none', color: '#18181a' },
  },
  SOURCE_TITLE_INPUT_CLASS: {
    maxWidth: '100%',
    borderRadius: '6px',
    borderColor: 'transparent',
    bgcolor: 'transparent',
    px: '6px',
    py: 0,
    fontSize: '18px',
    fontWeight: 600,
    lineHeight: '1.5',
    boxShadow: 'none',
    '&:hover': { borderColor: '#eceef1', bgcolor: '#fff' },
    '&:focus-visible': { borderColor: '#eceef1', bgcolor: '#fff', boxShadow: 'none', outline: 'none' },
  },
  SOURCE_STEP_TITLE_EDIT_CLASS: {
    display: 'inline-grid',
    width: '100%',
    maxWidth: '100%',
    minWidth: 0,
    gridTemplateColumns: 'auto minmax(0,1fr)',
    alignItems: 'center',
    gap: '6px',
    fontSize: '15px',
    fontWeight: 600,
    '& > span:first-child': { whiteSpace: 'nowrap', color: '#18181a' },
  },
  SOURCE_EDIT_INPUT_CLASS: {
    boxSizing: 'border-box',
    minWidth: 0,
    maxWidth: '100%',
    resize: 'none',
    overflowX: 'hidden',
    overflowY: 'hidden',
    borderRadius: '6px',
    borderColor: 'transparent',
    bgcolor: 'transparent',
    px: '6px',
    py: '2px',
    lineHeight: '1.65',
    overflowWrap: 'anywhere',
    boxShadow: 'none',
    fieldSizing: 'fixed',
    '&:hover': { borderColor: '#eceef1', bgcolor: '#fff' },
    '&:focus-visible': { borderColor: '#eceef1', bgcolor: '#fff', boxShadow: 'none', outline: 'none' },
  },
  SOURCE_COLLAPSIBLE_EDITOR_CLASS: {
    display: 'grid',
    minWidth: 0,
    width: '100%',
    maxWidth: '100%',
    gap: '8px',
  },
  SOURCE_COLLAPSIBLE_HEAD_CLASS: {
    display: 'grid',
    minHeight: '38px',
    width: '100%',
    cursor: 'pointer',
    gridTemplateColumns: 'minmax(0,1fr) auto',
    alignItems: 'center',
    gap: '10px',
    borderRadius: '10px',
    border: '1px solid',
    borderColor: '#eceef1',
    bgcolor: '#fff',
    px: '12px',
    py: '6px',
    textAlign: 'left',
    color: '#858b9c',
    boxShadow: 'inset 0 1px 0 rgba(255,255,255,0.74)',
    '&:hover': { borderColor: '#d1d5db', bgcolor: '#fff', color: '#18181a' },
    '&:focus-visible': { outline: 'none' },
  },
  SOURCE_COLLAPSIBLE_PREVIEW_CLASS: {
    minWidth: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    fontSize: '12px',
    lineHeight: '1.5',
  },
  SOURCE_COLLAPSIBLE_PREVIEW_MUTED_CLASS: {
    color: '#858b9c',
  },
  SOURCE_COLLAPSIBLE_TOGGLE_CLASS: {
    display: 'inline-flex',
    height: '26px',
    flexShrink: 0,
    alignItems: 'center',
    gap: '5px',
    borderRadius: '9999px',
    border: '1px solid',
    borderColor: '#eceef1',
    bgcolor: '#fff',
    px: '9px',
    fontSize: '12px',
    fontWeight: 600,
    lineHeight: 'none',
    color: '#858b9c',
  },
  SOURCE_ACTION_EDITOR_CLASS: {
    display: 'grid',
    width: 'min(820px,100%)',
    gap: '6px',
  },
  SOURCE_ACTION_LIST_CLASS: {
    display: 'flex',
    maxHeight: '84px',
    flexWrap: 'wrap',
    gap: '6px',
    overflow: 'auto',
  },
  SOURCE_ACTION_LIST_EDITABLE_CLASS: {
    minWidth: 0,
    flex: 1,
    alignItems: 'center',
  },
  SOURCE_ACTION_TOKEN_CLASS: {
    display: 'inline-flex',
    maxWidth: 'min(100%,320px)',
    alignItems: 'center',
    gap: '4px',
    my: '2px',
    mr: '4px',
  },
  SOURCE_ACTION_EDIT_BUTTON_CLASS: {
    display: 'inline-flex',
    minWidth: 0,
    cursor: 'text',
    border: 0,
    bgcolor: 'transparent',
    p: 0,
    color: 'inherit',
    '&:focus-visible': { borderRadius: '9999px', outline: '2px solid #18181a', outlineOffset: '2px' },
  },
  SOURCE_ACTION_REMOVE_CLASS: {
    display: 'grid',
    width: '16px',
    height: '16px',
    transform: 'scale(0.86)',
    placeItems: 'center',
    borderRadius: '9999px',
    border: 0,
    bgcolor: 'transparent',
    p: 0,
    fontSize: '12px',
    color: '#858b9c',
    opacity: 0,
    transition: 'opacity 0.14s, transform 0.14s, color 0.14s, background 0.14s',
    '&[data-token-group]:hover': { transform: 'scale(1)', opacity: 1, bgcolor: '#f2f3f5', color: '#18181a' },
    '&[data-token-group]': { pointerEvents: 'auto' },
  },
  SOURCE_ACTION_ADD_CLASS: {
    display: 'inline-flex',
    cursor: 'pointer',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '4px',
    height: '24px',
    borderRadius: '9999px',
    border: '0.5px solid',
    borderColor: '#e3e7f1',
    bgcolor: '#fff',
    px: '8px',
    fontSize: '12px',
    fontWeight: 400,
    lineHeight: 'none',
    color: '#858b9c',
    boxShadow: 'none',
    transition: 'background-color 0.15s',
    '&:hover': { borderColor: '#04756f', bgcolor: '#fff', color: '#18181a' },
    '&:focus-visible': { borderColor: '#04756f', boxShadow: 'none', outline: 'none', color: '#18181a' },
  },
  SOURCE_ACTION_PICKER_CLASS: {
    display: 'inline-flex',
    minWidth: 'min(280px,100%)',
    maxWidth: '100%',
  },
  SOURCE_ACTION_SELECT_CLASS: {
    height: '26px',
    minWidth: 0,
    width: '100%',
    maxWidth: '100%',
    borderRadius: '9999px',
    border: '1px solid',
    borderColor: '#eceef1',
    bgcolor: '#fff',
    px: '8px',
    fontSize: '12px',
    lineHeight: '1.4',
    boxShadow: 'none',
  },
  SOURCE_EDIT_HINT_CLASS: {
    flexShrink: 0,
    fontSize: '11px',
    color: '#858b9c',
    opacity: 0,
    '&[data-action-editor]:hover': { opacity: 1 },
  },
  SOURCE_SELECT_CLASS: {
    minWidth: '168px',
  },
  CONDITION_EDITOR_CLASS: {
    display: 'grid',
    minWidth: 0,
    width: '100%',
    maxWidth: '100%',
    gridTemplateColumns: '1fr',
    alignItems: 'flex-start',
    columnGap: '10px',
    rowGap: '8px',
    '@media (min-width: 1500px)': {
      gridTemplateColumns: 'minmax(160px,220px) minmax(0,1fr)',
    },
  },
  CONDITION_READABLE_CLASS: {
    gridColumn: '1 / -1',
    fontSize: '12px',
    lineHeight: '1.55',
    color: '#858b9c',
  },
  CONDITION_PRESET_CLASS: {
    minWidth: '168px',
  },
  CONDITION_INPUT_CLASS: {
    width: '100%',
    minWidth: 0,
  },
  RETRY_POLICY_EDITOR_CLASS: {
    display: 'grid',
    minWidth: 0,
    width: '100%',
    maxWidth: '100%',
    gridTemplateColumns: '1fr',
    alignItems: 'flex-start',
    columnGap: '10px',
    rowGap: '8px',
    '@media (min-width: 1500px)': {
      gridTemplateColumns: '120px minmax(180px,240px) minmax(0,1fr)',
    },
  },
  RETRY_POLICY_FIELD_CLASS: {
    display: 'grid',
    minWidth: 0,
    gap: '4px',
    '& > span': { fontSize: '11px', fontWeight: 600, lineHeight: '1.3', color: '#858b9c' },
  },
  FLOW_RULE_EDITOR_CLASS: {
    display: 'grid',
    width: 'min(1120px,100%)',
    gap: '10px',
  },
  FLOW_RULE_HEAD_CLASS: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '8px',
    fontSize: '12px',
    fontWeight: 600,
    color: '#858b9c',
  },
  FLOW_RULE_LIST_CLASS: {
    display: 'grid',
    gap: '10px',
  },
  FLOW_RULE_ITEM_CLASS: {
    display: 'grid',
    minWidth: 0,
    maxWidth: '100%',
    columnGap: '12px',
    rowGap: '10px',
    borderRadius: '12px',
    border: '1px solid',
    borderColor: '#eceef1',
    bgcolor: '#fafafa',
    p: '12px',
  },
  FLOW_RULE_FIELD_CLASS: {
    display: 'grid',
    minWidth: 0,
    gap: '4px',
    '& > span': { fontSize: '11px', fontWeight: 600, lineHeight: '1.3', color: '#858b9c' },
  },
  FLOW_RULE_FIELD_TARGET_CLASS: {
    gridArea: 'target',
  },
  FLOW_RULE_FIELD_LABEL_CLASS: {
    gridArea: 'label',
  },
  FLOW_RULE_FIELD_CONDITION_CLASS: {
    gridArea: 'condition',
  },
  FLOW_RULE_FIELD_PRIORITY_CLASS: {
    gridArea: 'priority',
  },
  FLOW_RULE_CONDITION_CONTROLS_CLASS: {
    display: 'grid',
    minWidth: 0,
    maxWidth: '100%',
    gridTemplateColumns: '1fr',
    alignItems: 'flex-start',
    gap: '8px',
    '@media (min-width: 1500px)': {
      gridTemplateColumns: 'minmax(180px,240px) minmax(0,1fr)',
    },
  },
  FLOW_RULE_TARGET_CLASS: {
    width: '100%',
    minWidth: 0,
  },
  FLOW_RULE_LABEL_INPUT_CLASS: {
    width: '100%',
    minWidth: 0,
  },
  FLOW_RULE_CONDITION_INPUT_CLASS: {
    width: '100%',
    minWidth: 0,
    resize: 'none',
  },
  FLOW_RULE_PRIORITY_CLASS: {
    width: '100%',
    minWidth: 0,
  },
  FLOW_RULE_DELETE_CLASS: {
    gridArea: 'delete',
    mt: '19px',
  },
  FLOW_RULE_EMPTY_CLASS: {
    borderRadius: '12px',
    border: '1px dashed',
    borderColor: '#eceef1',
    bgcolor: '#fafafa',
    p: '10px 12px',
    fontSize: '12px',
    color: '#858b9c',
  },
  NODE_DELETE_CONFIRM_CLASS: {
    display: 'grid',
    gap: '8px',
    '& p': { m: 0 },
    '& ul': { m: 0, pl: '18px' },
  },

  // —— 流程图 ——
  FLOW_ZOOM_TOOLBAR_CLASS: {
    mt: '-2px',
    mb: '12px',
    display: 'flex',
    minHeight: '40px',
    alignItems: 'center',
    gap: '8px',
    fontSize: '12px',
    color: '#858b9c',
  },
  FLOW_ZOOM_BUTTON_BASE: {
    display: 'inline-flex',
    flexShrink: 0,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '9px',
    border: '0.5px solid',
    borderColor: '#e3e7f1',
    bgcolor: '#fff',
    fontSize: '12px',
    fontWeight: 400,
    lineHeight: 'none',
    color: '#757f9c',
    boxShadow: 'none',
    transition: 'background-color 0.15s',
    '&:hover': { borderColor: '#cbd3e6', bgcolor: '#fff', color: '#18181a' },
    '&:focus-visible': { borderColor: '#cbd3e6', boxShadow: 'none', outline: 'none' },
    '&[aria-pressed="true"]': { borderColor: '#04756f', bgcolor: '#f3fbf8', fontWeight: 500, color: '#18181a' },
  },
  FLOW_ZOOM_STEP_BUTTON_CLASS: {
    display: 'inline-flex',
    flexShrink: 0,
    alignItems: 'center',
    justifyContent: 'center',
    width: '28px',
    minWidth: '34px',
    borderRadius: '9px',
    border: '0.5px solid',
    borderColor: '#e3e7f1',
    bgcolor: '#fff',
    fontSize: '12px',
    fontWeight: 400,
    lineHeight: 'none',
    color: '#757f9c',
    boxShadow: 'none',
    transition: 'background-color 0.15s',
    '&:hover': { borderColor: '#cbd3e6', bgcolor: '#fff', color: '#18181a' },
    '&:focus-visible': { borderColor: '#cbd3e6', boxShadow: 'none', outline: 'none' },
    '&[aria-pressed="true"]': { borderColor: '#04756f', bgcolor: '#f3fbf8', fontWeight: 500, color: '#18181a' },
  },
  FLOW_ZOOM_PRESET_BUTTON_CLASS: {
    display: 'inline-flex',
    flexShrink: 0,
    alignItems: 'center',
    justifyContent: 'center',
    height: '28px',
    minWidth: '34px',
    borderRadius: '9px',
    border: '0.5px solid',
    borderColor: '#e3e7f1',
    bgcolor: '#fff',
    px: '10px',
    fontSize: '12px',
    fontWeight: 400,
    lineHeight: 'none',
    color: '#757f9c',
    boxShadow: 'none',
    transition: 'background-color 0.15s',
    '&:hover': { borderColor: '#cbd3e6', bgcolor: '#fff', color: '#18181a' },
    '&:focus-visible': { borderColor: '#cbd3e6', boxShadow: 'none', outline: 'none' },
    '&[aria-pressed="true"]': { borderColor: '#04756f', bgcolor: '#f3fbf8', fontWeight: 500, color: '#18181a' },
  },
  FLOW_ZOOM_VALUE_CLASS: {
    display: 'inline-flex',
    height: '28px',
    minWidth: '42px',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '9px',
    bgcolor: '#fafafa',
    px: '8px',
    textAlign: 'center',
    fontFamily: 'monospace',
    fontSize: '12px',
    lineHeight: 'none',
    color: '#18181a',
  },
  FLOW_CLASS: {
    display: 'block',
    minHeight: 0,
    flex: 1,
    overflow: 'auto',
    px: 'clamp(18px,3vw,40px)',
    py: 'clamp(18px,2.8vw,34px)',
    pb: '64px',
  },
  FLOW_ZOOM_SHELL_CLASS: {
    position: 'relative',
    mx: 0,
    minWidth: '100%',
  },
  FLOW_GRAPH_CANVAS_CLASS: {
    position: 'absolute',
    top: 0,
    left: 0,
    transformOrigin: 'top left',
    borderRadius: '18px',
    boxSizing: 'border-box',
    backgroundImage:
      'radial-gradient(circle at 40px 40px, rgba(18,128,115,0.05), transparent 240px), linear-gradient(90deg, rgba(218,211,199,0.38) 1px, transparent 1px), linear-gradient(rgba(218,211,199,0.26) 1px, transparent 1px)',
    backgroundSize: 'auto, 72px 72px, 72px 72px',
  },
  FLOW_EDGES_CLASS: {
    pointerEvents: 'none',
    position: 'absolute',
    top: 0,
    left: 0,
    zIndex: 2,
    overflow: 'visible',
  },
  FLOW_EDGE_PATH_CLASS: {
    fill: 'none',
    stroke: '#bfb09a',
    strokeWidth: '1.3',
    strokeDasharray: '6 14',
    vectorEffect: 'non-scaling-stroke',
    strokeLinecap: 'round',
    strokeLinejoin: 'round',
    opacity: 0.5,
  },
  FLOW_EDGE_LABEL_BASE_CLASS: {
    pointerEvents: 'none',
    position: 'absolute',
    zIndex: 4,
    maxWidth: '176px',
    transform: 'translate(-50%,-50%)',
    overflow: 'hidden',
    borderRadius: '9999px',
    border: '1px solid',
    borderColor: '#d7cbbb',
    bgcolor: 'rgba(255,253,248,0.98)',
    px: '9px',
    py: '4px',
    fontSize: '11px',
    lineHeight: '1.35',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    color: '#5f574b',
    boxShadow: '0 8px 18px rgba(38,32,23,0.1)',
  },
  FLOW_ROOT_POSITION_CLASS: {
    position: 'absolute',
    zIndex: 6,
  },
  FLOW_NODE_POSITION_CLASS: {
    position: 'absolute',
    zIndex: 7,
  },
  FLOW_NODE_SHELL_CLASS: {
    display: 'grid',
    height: '100%',
    width: '100%',
    maxWidth: 'none',
    justifyItems: 'stretch',
    gap: '8px',
  },
  FLOW_NODE_CLASS: {
    position: 'relative',
    isolation: 'isolate',
    boxSizing: 'border-box',
    display: 'grid',
    height: '100%',
    minHeight: 0,
    width: '100%',
    cursor: 'pointer',
    gridTemplateRows: 'auto auto auto auto minmax(0,1fr)',
    gap: '7px',
    overflow: 'hidden',
    borderRadius: '10px',
    border: '1px solid',
    borderColor: '#eceef1',
    bgcolor: '#fffefd',
    p: '14px 15px',
    textAlign: 'left',
    userSelect: 'text',
    color: '#18181a',
    '&:focus-visible': { outline: '2px solid #18181a', outlineOffset: '2px' },
  },
  FLOW_NODE_ROOT_CLASS: {
    position: 'relative',
    zIndex: 1,
    height: '100%',
    minHeight: 0,
    width: '100%',
    justifySelf: 'start',
    bgcolor: '#f2f0eb',
    boxShadow: '0 14px 34px rgba(37,32,24,0.08)',
  },
  FLOW_NODE_ACTIVE_CLASS: {
    borderColor: '#04756f',
    boxShadow: '0 8px 22px rgba(4,117,111,0.08)',
  },
  FLOW_NODE_CHANGED_CLASS: {
    borderColor: '#04756f',
    bgcolor: '#effaf6',
    boxShadow: '0 12px 30px rgba(4,117,111,0.12)',
    transitionProperty: 'background, border-color, box-shadow',
    transitionDuration: '450ms',
  },
  FLOW_NODE_DIRTY_CLASS: {
    bgcolor: '#fffdf8',
    boxShadow: 'inset 3px 0 0 #d8c7a4',
  },
  FLOW_NODE_UPDATING_CLASS: {
    animation: 'pulse 2s cubic-bezier(0.4,0,0.6,1) infinite',
  },
  FLOW_NODE_BADGES_CLASS: {
    display: 'flex',
    maxHeight: '28px',
    flexWrap: 'wrap',
    gap: '6px',
    overflow: 'hidden',
  },
  FLOW_NODE_SUMMARY_CLASS: {
    m: '2px 0 0',
    display: '-webkit-box',
    WebkitLineClamp: 3,
    WebkitBoxOrient: 'vertical',
    overflow: 'hidden',
    fontSize: '13px',
    lineHeight: '1.5',
    overflowWrap: 'anywhere',
    color: '#858b9c',
  },
  FLOW_COMPACT_META_CLASS: {
    display: 'grid',
    minHeight: 0,
    alignContent: 'flex-start',
    gap: '6px',
    overflow: 'hidden',
  },
  FLOW_COMPACT_ROW_CLASS: {
    display: 'grid',
    minWidth: 0,
    gridTemplateColumns: '34px minmax(0,1fr)',
    alignItems: 'flex-start',
    gap: '8px',
    '& > span:first-child': { fontSize: '12px', fontWeight: 600, lineHeight: '24px', color: '#858b9c' },
  },
  FLOW_ROUTE_COUNT_CLASS: {
    width: 'fit-content',
    borderRadius: '9999px',
    border: '1px dashed',
    borderColor: '#eceef1',
    bgcolor: '#fafafa',
    px: '8px',
    py: '3px',
    fontSize: '11px',
    lineHeight: '1.3',
    color: '#858b9c',
  },
  FLOW_META_CLASS: {
    mt: '6px',
    display: 'grid',
    gap: '8px',
  },
  FLOW_META_ROW_CLASS: {
    display: 'grid',
    gap: '5px',
  },
  FLOW_META_LABEL_CLASS: {
    fontSize: '11px',
    fontWeight: 600,
    color: '#858b9c',
  },
  FLOW_CHIP_LIST_CLASS: {
    display: 'flex',
    maxHeight: '54px',
    flexWrap: 'wrap',
    gap: '6px',
    overflow: 'hidden',
  },
  FLOW_CHIP_CLASS: {
    maxWidth: '100%',
    overflow: 'hidden',
    borderRadius: '9999px',
    border: '1px solid',
    borderColor: '#eceef1',
    bgcolor: '#fafafa',
    px: '8px',
    py: '4px',
    fontSize: '11px',
    lineHeight: '1.4',
    overflowWrap: 'anywhere',
    color: '#858b9c',
  },
  FLOW_CHIP_MUTED_CLASS: {
    color: '#858b9c',
  },
  FLOW_CHIP_TERMINAL_CLASS: {},

  // —— 操作 chips ——
  ACTION_LIST_CLASS: {
    display: 'flex',
    maxHeight: '84px',
    flexWrap: 'wrap',
    gap: '6px',
    overflow: 'auto',
  },
  ACTION_EMPTY_CLASS: {
    color: '#858b9c',
  },
  ACTION_CHIP_BASE_CLASS: {
    maxWidth: '100%',
    overflow: 'hidden',
    borderRadius: '9999px',
    border: '1px solid',
    borderColor: '#eceef1',
    bgcolor: '#fafafa',
    px: '8px',
    py: '4px',
    fontSize: '11px',
    lineHeight: '1.4',
    overflowWrap: 'anywhere',
    color: '#858b9c',
  },
  ACTION_CHIP_TOOL_CLASS: {
    cursor: 'help',
    borderColor: '#b9ded5',
    bgcolor: '#e9f6f2',
    color: '#075f59',
  },
  ACTION_CHIP_TOOL_EXISTING_CLASS: {
    borderColor: '#bbf7d0',
    bgcolor: '#f0fdf4',
    color: '#166534',
  },
  ACTION_CHIP_TOOL_PENDING_CLASS: {
    borderColor: '#fed7aa',
    bgcolor: '#fffbeb',
    color: '#92400e',
  },
  ACTION_CHIP_TOOL_REJECTED_CLASS: {
    borderColor: '#fecaca',
    bgcolor: '#fef2f2',
    color: '#991b1b',
  },
  ACTION_CHIP_TOOL_INCOMPLETE_CLASS: {
    borderColor: '#eceef1',
    bgcolor: '#f7f5ef',
    color: '#858b9c',
  },
  ACTION_CHIP_ADDED_CLASS: {
    borderColor: '#9bd3b0',
    bgcolor: '#e8f6ee',
    color: '#135f36',
  },
  ACTION_CHIP_ADDED_TYPING_CLASS: {
    boxShadow: 'inset 0 -2px 0 rgba(19,95,54,0.22)',
  },
  ACTION_CHIP_ADDED_SETTLED_CLASS: {
    bgcolor: '#eef9f2',
  },
  ACTION_CHIP_REMOVED_CLASS: {
    borderColor: '#f0b7b2',
    bgcolor: '#fff1f0',
    color: '#8c2b2b',
  },
  INLINE_REMOVE_CLASS: {
    borderRadius: '4px',
    bgcolor: '#fef3c7',
    px: '2px',
    py: '1px',
    fontWeight: 600,
    color: '#713f12',
    animation: 'skill-inline-remove 520ms ease both',
  },
  INLINE_ADD_CLASS: {
    borderRadius: '4px',
    bgcolor: '#dcfce7',
    px: '2px',
    py: '1px',
    fontWeight: 600,
    color: '#14532d',
  },
  INLINE_ADD_SETTLED_CLASS: {
    bgcolor: '#dcfce7',
  },
  SELECTION_MARK_CLASS: {
    position: 'absolute',
    right: '10px',
    bottom: '10px',
    display: 'inline-grid',
    width: '22px',
    height: '22px',
    placeItems: 'center',
    borderRadius: '9999px',
    bgcolor: '#04756f',
    fontSize: '12px',
    color: '#fff',
  },

  // —— 保存审阅 + 工具详情弹窗 ——
  SAVE_REVIEW_FORM_CLASS: {
    mb: '16px',
    display: 'grid',
    gridTemplateColumns: 'repeat(3, minmax(0,1fr))',
    gap: '12px',
    '@media (max-width: 640px)': { gridTemplateColumns: '1fr' },
  },
  SAVE_REVIEW_FORM_LABEL_CLASS: {
    display: 'grid',
    gap: '6px',
    fontSize: '12px',
    color: '#858b9c',
  },
  SAVE_REVIEW_DIFF_CLASS: {
    display: 'grid',
    maxHeight: '420px',
    gap: '10px',
    overflow: 'auto',
  },
  SAVE_REVIEW_DIFF_ROW_CLASS: {
    borderRadius: '10px',
    border: '1px solid',
    borderColor: '#eceef1',
    bgcolor: '#fafafa',
    p: '10px 12px',
  },
  SAVE_REVIEW_DIFF_PATH_CLASS: {
    mb: '6px',
    fontSize: '12px',
    fontWeight: 600,
    color: '#858b9c',
  },
  SAVE_REVIEW_ACTION_DIFF_CLASS: {
    mt: '4px',
    display: 'flex',
    alignItems: 'flex-start',
    gap: '8px',
  },
  SAVE_REVIEW_ACTION_DIFF_OLD_CLASS: {},
  SAVE_REVIEW_ACTION_DIFF_NEW_CLASS: {},
  SAVE_REVIEW_DIFF_SIGN_CLASS: {
    width: '12px',
    flexShrink: 0,
    fontFamily: 'monospace',
    fontSize: '13px',
    fontWeight: 600,
    lineHeight: '24px',
  },
  SAVE_REVIEW_DIFF_SIGN_OLD_CLASS: {
    color: '#991b1b',
  },
  SAVE_REVIEW_DIFF_SIGN_NEW_CLASS: {
    color: '#166534',
  },
  DIFF_OLD_CLASS: {
    fontFamily: 'monospace',
    fontSize: '12px',
    lineHeight: '1.6',
    whiteSpace: 'pre-wrap',
    color: '#991b1b',
  },
  DIFF_NEW_CLASS: {
    fontFamily: 'monospace',
    fontSize: '12px',
    lineHeight: '1.6',
    whiteSpace: 'pre-wrap',
    color: '#166534',
  },
  TOOL_SUGGESTION_DETAIL_CLASS: {
    display: 'grid',
    gap: '10px',
  },
  TOOL_SUGGESTION_DETAIL_FOOTER_CLASS: {
    display: 'flex',
    width: '100%',
    flexWrap: 'wrap',
    justifyContent: 'flex-end',
    gap: '8px',
  },
  TOOL_SUGGESTION_DETAIL_PRE_CLASS: {
    m: 0,
    maxHeight: '220px',
    overflow: 'auto',
    borderRadius: '10px',
    border: '1px solid',
    borderColor: '#eceef1',
    bgcolor: '#fafafa',
    p: '12px',
    fontSize: '12px',
  },

  // —— 来源内联输入 ——
  SOURCE_INPUT_CLASS: {
    boxSizing: 'border-box',
    height: 'auto',
    minHeight: 0,
    minWidth: 0,
    width: '100%',
    maxWidth: '100%',
    borderRadius: '6px',
    border: '1px solid',
    borderColor: 'transparent',
    bgcolor: 'transparent',
    px: '6px',
    py: '2px',
    fontSize: '13px',
    lineHeight: '1.65',
    color: '#18181a',
    boxShadow: 'none',
    transition: 'background-color 0.15s',
    fieldSizing: 'fixed',
    '&:hover': { borderColor: '#eceef1', bgcolor: '#fff' },
    '&:focus-visible': { borderColor: '#eceef1', bgcolor: '#fff', boxShadow: 'none', outline: 'none' },
  },
} satisfies Record<string, SxProps<Theme>>

// ===========================================================================
// 动态 helper —— 返回 SxProps<Theme>
// ===========================================================================

export type ToolStatusBadgeVariant = 'success' | 'error' | 'running' | 'pending' | 'muted'

const TOOL_STATUS_BADGE_VARIANTS: Record<ToolStatusBadgeVariant, SxProps<Theme>> = {
  success: { color: '#166534', bgcolor: '#f0fdf4', borderColor: '#bbf7d0' },
  error: { color: '#991b1b', bgcolor: '#fef2f2', borderColor: '#fecaca' },
  running: { color: '#854d0e', bgcolor: '#fefce8', borderColor: '#fde68a' },
  pending: { color: '#92400e', bgcolor: '#fffbeb', borderColor: '#fed7aa' },
  muted: { color: '#858b9c', bgcolor: '#f7f5ef', borderColor: '#eceef1' },
}

export function toolStatusBadgeClass(status: ToolStatusBadgeVariant): SxProps<Theme> {
  return [distillTokens.TOOL_STATUS_BADGE_BASE_CLASS, TOOL_STATUS_BADGE_VARIANTS[status]] as SxProps<Theme>
}

export function flowZoomPresetButtonClass(active: boolean): SxProps<Theme> {
  const base = distillTokens.FLOW_ZOOM_PRESET_BUTTON_CLASS
  if (active) {
    return [
      base,
      {
        borderColor: '#04756f',
        bgcolor: '#f3fbf8',
        fontWeight: 500,
        color: '#18181a',
      },
    ]
  }
  return base
}

export function chatRowClass(role: 'user' | 'assistant'): SxProps<Theme> {
  return [distillTokens.CHAT_ROW_BASE_CLASS, role === 'user' ? distillTokens.CHAT_ROW_USER_CLASS : {}]
}

export function chatBubbleClass({
  role,
  editing = false,
  hasAttachments = false,
}: {
  role: 'user' | 'assistant'
  editing?: boolean
  hasAttachments?: boolean
}): SxProps<Theme> {
  if (role === 'user') {
    if (hasAttachments && editing) {
      return [
        distillTokens.CHAT_BUBBLE_BASE_CLASS,
        distillTokens.CHAT_BUBBLE_USER_EDITING_ATTACHMENTS_CLASS,
      ]
    }
    if (hasAttachments) {
      return [
        distillTokens.CHAT_BUBBLE_BASE_CLASS,
        distillTokens.CHAT_BUBBLE_USER_HAS_ATTACHMENTS_CLASS,
      ]
    }
    if (editing) {
      return [
        distillTokens.CHAT_BUBBLE_BASE_CLASS,
        distillTokens.CHAT_BUBBLE_USER_CLASS,
        distillTokens.CHAT_BUBBLE_USER_EDITING_CLASS,
      ]
    }
    return [distillTokens.CHAT_BUBBLE_BASE_CLASS, distillTokens.CHAT_BUBBLE_USER_CLASS]
  }
  return [
    distillTokens.CHAT_BUBBLE_BASE_CLASS,
    distillTokens.CHAT_BUBBLE_ASSISTANT_CLASS,
    editing ? { boxShadow: '0 0 0 1px rgba(4,117,111,0.3)' } : {},
  ]
}

export function uploadItemClass(status: 'uploading' | 'ready' | 'error'): SxProps<Theme> {
  return [
    distillTokens.UPLOAD_ITEM_BASE_CLASS,
    status === 'error' ? distillTokens.UPLOAD_ITEM_ERROR_CLASS : {},
  ]
}

const isActive = (path: string, paths: string[]): boolean => paths.includes(path)

export function distillSourceSectionClass(
  path: string,
  selectedPaths: string[],
  highlightedPaths: string[],
  updatingPaths: string[],
  dirtyPaths: string[],
): SxProps<Theme> {
  return [
    distillTokens.SOURCE_SECTION_CLASS,
    isActive(path, selectedPaths) ? distillTokens.SOURCE_SECTION_ACTIVE_CLASS : {},
    isActive(path, highlightedPaths) ? distillTokens.SOURCE_SECTION_CHANGED_CLASS : {},
    isActive(path, updatingPaths) ? distillTokens.SOURCE_SECTION_UPDATING_CLASS : {},
    isActive(path, dirtyPaths) ? distillTokens.SOURCE_SECTION_DIRTY_CLASS : {},
  ]
}

export function distillFlowNodeClass(
  path: string,
  isRoot: boolean,
  selectedPaths: string[],
  highlightedPaths: string[],
  updatingPaths: string[],
  dirtyPaths: string[],
): SxProps<Theme> {
  return [
    distillTokens.FLOW_NODE_CLASS,
    isRoot ? distillTokens.FLOW_NODE_ROOT_CLASS : {},
    isActive(path, selectedPaths) ? distillTokens.FLOW_NODE_ACTIVE_CLASS : {},
    isActive(path, highlightedPaths) ? distillTokens.FLOW_NODE_CHANGED_CLASS : {},
    isActive(path, updatingPaths) ? distillTokens.FLOW_NODE_UPDATING_CLASS : {},
    isActive(path, dirtyPaths) ? distillTokens.FLOW_NODE_DIRTY_CLASS : {},
  ]
}

export function flowEdgeLabelClass(tone?: string): SxProps<Theme> {
  return [
    distillTokens.FLOW_EDGE_LABEL_BASE_CLASS,
    tone === 'branch' ? { maxWidth: '232px', opacity: 0.94 } : {},
    tone === 'parallel'
      ? {
          maxWidth: '232px',
          borderColor: 'rgba(15,118,110,0.24)',
          bgcolor: 'rgba(236,253,245,0.96)',
          color: '#0f766e',
        }
      : {},
    tone === 'return' ? { borderStyle: 'dashed', opacity: 0.88 } : {},
  ]
}

export function actionChipClass({
  toolName,
  status,
  variant,
}: {
  toolName?: string
  status?: string
  variant?: 'added' | 'removed' | 'typing' | 'settled' | 'marked'
}): SxProps<Theme> {
  const toolVariant: SxProps<Theme> =
    status === 'existing' || status === 'accepted' || status === 'created'
      ? distillTokens.ACTION_CHIP_TOOL_EXISTING_CLASS
      : status === 'pending'
        ? distillTokens.ACTION_CHIP_TOOL_PENDING_CLASS
        : status === 'rejected'
          ? distillTokens.ACTION_CHIP_TOOL_REJECTED_CLASS
          : status === 'incomplete'
            ? distillTokens.ACTION_CHIP_TOOL_INCOMPLETE_CLASS
            : distillTokens.ACTION_CHIP_TOOL_CLASS

  return [
    distillTokens.ACTION_CHIP_BASE_CLASS,
    toolName ? toolVariant : {},
    variant === 'removed' ? distillTokens.ACTION_CHIP_REMOVED_CLASS : {},
    variant === 'added' ? distillTokens.ACTION_CHIP_ADDED_CLASS : {},
    variant === 'typing' ? distillTokens.ACTION_CHIP_ADDED_TYPING_CLASS : {},
    variant === 'settled' ? distillTokens.ACTION_CHIP_ADDED_SETTLED_CLASS : {},
  ]
}