FROM node:22-alpine

WORKDIR /app

ENV NODE_ENV=development
ENV PORT=3000

RUN apk add --no-cache \
    ca-certificates \
    libgcc \
    libstdc++ \
    git \
    python3 \
    make \
    g++ \
    && rm -rf /var/cache/apk/*

COPY package.json package-lock.json ./

RUN npm install --legacy-peer-deps

COPY . .

EXPOSE 3000 5173

CMD ["npm", "run", "dev"]
