/**
 * Ollama 本地模型提供商
 *
 * baseUrl: http://localhost:11434
 * authType: none（本地部署，无需 API Key）
 *
 * Ollama 支持运行各种开源模型：
 * - Llama 3.1
 * - Qwen 2.5
 * - DeepSeek R1
 * - Mistral
 * - Gemma 2
 */

import type { ProviderInfo, ModelInfo } from './modelCatalog.js';
import { PROVIDER_ENDPOINTS } from '../../shared/data/providerEndpoints.js';

/** Ollama 预设模型列表（用户可自行安装其他模型） */
const OLLAMA_MODELS: ModelInfo[] = [
  {
    id: 'llama3.1',
    name: 'Llama 3.1',
    provider: 'ollama',
    description: 'Ollama 本地部署 Llama 3.1',
    contextWindow: 128_000,
    maxTokens: 4_096,
    input: ['text', 'image'],
    capabilities: ['general'],
    supportsTools: true,
    supportsStreaming: true,
    apiType: 'openai-completions',
    pricing: { isFree: true },
    isRecommended: true,
  },
  {
    id: 'llama3.1:70b',
    name: 'Llama 3.1 70B',
    provider: 'ollama',
    description: 'Ollama 本地部署 Llama 3.1 70B',
    contextWindow: 128_000,
    maxTokens: 4_096,
    input: ['text', 'image'],
    capabilities: ['reasoning', 'general'],
    supportsTools: true,
    supportsStreaming: true,
    apiType: 'openai-completions',
    pricing: { isFree: true },
  },
  {
    id: 'qwen2.5',
    name: 'Qwen 2.5',
    provider: 'ollama',
    description: 'Ollama 本地部署 Qwen 2.5',
    contextWindow: 128_000,
    maxTokens: 4_096,
    input: ['text'],
    capabilities: ['general', 'code'],
    supportsTools: true,
    supportsStreaming: true,
    apiType: 'openai-completions',
    pricing: { isFree: true },
    isRecommended: true,
  },
  {
    id: 'deepseek-r1',
    name: 'DeepSeek R1',
    provider: 'ollama',
    description: 'Ollama 本地部署 DeepSeek R1',
    contextWindow: 128_000,
    maxTokens: 4_096,
    input: ['text'],
    capabilities: ['reasoning', 'general'],
    supportsTools: true,
    supportsStreaming: true,
    apiType: 'openai-completions',
    reasoning: true,
    pricing: { isFree: true },
  },
  {
    id: 'deepseek-r1:70b',
    name: 'DeepSeek R1 70B',
    provider: 'ollama',
    description: 'Ollama 本地部署 DeepSeek R1 70B',
    contextWindow: 128_000,
    maxTokens: 4_096,
    input: ['text'],
    capabilities: ['reasoning', 'general'],
    supportsTools: true,
    supportsStreaming: true,
    apiType: 'openai-completions',
    reasoning: true,
    pricing: { isFree: true },
  },
  {
    id: 'mistral',
    name: 'Mistral',
    provider: 'ollama',
    description: 'Ollama 本地部署 Mistral',
    contextWindow: 128_000,
    maxTokens: 4_096,
    input: ['text'],
    capabilities: ['general', 'code'],
    supportsTools: true,
    supportsStreaming: true,
    apiType: 'openai-completions',
    pricing: { isFree: true },
  },
  {
    id: 'gemma2',
    name: 'Gemma 2',
    provider: 'ollama',
    description: 'Ollama 本地部署 Gemma 2',
    contextWindow: 128_000,
    maxTokens: 4_096,
    input: ['text'],
    capabilities: ['general', 'costEffective'],
    supportsTools: true,
    supportsStreaming: true,
    apiType: 'openai-completions',
    pricing: { isFree: true },
  },
  {
    id: 'codellama',
    name: 'Code Llama',
    provider: 'ollama',
    description: 'Ollama 本地部署 Code Llama',
    contextWindow: 16_000,
    maxTokens: 4_096,
    input: ['text'],
    capabilities: ['code', 'general'],
    supportsTools: true,
    supportsStreaming: true,
    apiType: 'openai-completions',
    pricing: { isFree: true },
  },
  {
    id: 'phi3',
    name: 'Phi-3',
    provider: 'ollama',
    description: 'Ollama 本地部署 Phi-3 Mini',
    contextWindow: 128_000,
    maxTokens: 4_096,
    input: ['text'],
    capabilities: ['fast', 'general'],
    supportsTools: true,
    supportsStreaming: true,
    apiType: 'openai-completions',
    pricing: { isFree: true },
  },
  {
    id: 'nomic-embed-text',
    name: 'Nomic Embed Text',
    provider: 'ollama',
    description: 'Ollama 本地部署 Nomic Embedding',
    contextWindow: 8_192,
    maxTokens: 512,
    input: ['text'],
    capabilities: ['general'],
    supportsStreaming: true,
    apiType: 'openai-completions',
    pricing: { isFree: true },
  },
];

/** Ollama 提供商信息 */
export const OLLAMA_PROVIDER: ProviderInfo = {
  id: 'ollama',
  name: 'Ollama',
  baseUrl: PROVIDER_ENDPOINTS.ollama,
  authType: 'none',
  categories: ['local', 'llm'],
  docsPath: '/providers/ollama',
  models: OLLAMA_MODELS,
  isLocal: true,
  allowCustomBaseUrl: true,
  description: 'Ollama 本地模型运行平台',
  website: 'https://ollama.com',
};