import type { SxProps, Theme } from '@mui/material/styles';

/**
 * MUI `sx` translation of the chat conversation page styles.
 *
 * Every key is the camelCased equivalent of a `CHAT_*` export from the old
 * `chatPageStyles.ts` Tailwind class module. Colors are kept literal so the
 * visual design is byte-for-byte identical to the Tailwind version.
 */

export const chatTokens = {
  // Shared chat chrome
  iconButton: {
    display: 'inline-grid',
    width: '30px',
    height: '30px',
    flexShrink: 0,
    placeItems: 'center',
    borderRadius: '8px',
    borderWidth: 0,
    bgcolor: 'transparent',
    p: 0,
    color: '#757f9c',
    transition: 'background-color 0.15s, color 0.15s',
    '&:hover': { bgcolor: '#f1f2f5', color: '#18181a' },
  },

  // Main column + header
  main: {
    display: 'flex',
    minHeight: 0,
    minWidth: 0,
    flexDirection: 'column',
    bgcolor: '#fcfcfc',
  },
  header: {
    display: 'flex',
    height: '56px',
    flexShrink: 0,
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '12px',
    borderBottom: '1px solid #f4f4f4',
    pl: '18px',
    pr: '24px',
  },
  headerTitleStack: {
    display: 'flex',
    minWidth: 0,
    alignItems: 'flex-end',
    gap: '8px',
  },
  headerTitleName: {
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    fontSize: '14px',
    textTransform: 'capitalize',
    color: '#18181a',
  },
  headerTitleMeta: {
    flexShrink: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    fontSize: '10px',
    color: '#757f9c',
  },
  headerActions: {
    display: 'flex',
    flexShrink: 0,
    alignItems: 'center',
    gap: '6px',
  },

  // Message scroller
  messages: {
    minHeight: 0,
    flex: 1,
    overflowY: 'auto',
    px: '24px',
    pt: '22px',
    pb: '62px',
  },
  messageStack: {
    mx: 'auto',
    display: 'flex',
    width: '100%',
    maxWidth: '820px',
    flexDirection: 'column',
    gap: '20px',
  },

  messageItem: {
    display: 'flex',
    minWidth: 0,
    flexDirection: 'column',
  },
  queuedMessageItem: {
    order: 999,
  },
  messageRowBase: {
    display: 'flex',
    minWidth: 0,
  },
  messageRowUser: {
    justifyContent: 'flex-end',
  },
  messageRowAssistant: {
    justifyContent: 'flex-start',
  },

  bubbleBase: {
    position: 'relative',
    boxSizing: 'border-box',
    minWidth: 0,
    maxWidth: 'min(680px,92%)',
    fontSize: '14px',
    lineHeight: 1.7,
    overflowWrap: 'anywhere',
    color: '#18181a',
  },
  bubbleAssistant: {
    width: '100%',
    maxWidth: '100%',
    borderRadius: '14px',
    border: '0.5px solid #e3e7f1',
    bgcolor: 'background.paper',
    px: '18px',
    py: '14px',
    boxShadow: '0 1px 2px rgba(24,24,26,0.03)',
  },
  bubbleUser: {
    borderRadius: '14px',
    bgcolor: '#f6f6f6',
    px: '16px',
    py: '11px',
    color: '#18181a',
  },
  bubbleError: {
    borderColor: '#f38989',
    bgcolor: '#fce7e7',
    color: '#d20b0b',
  },

  // User plain answer + scheduled chip
  plainAnswer: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-end',
    gap: '6px',
    whiteSpace: 'pre-wrap',
  },
  messageModeChip: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '4px',
    borderRadius: '9999px',
    bgcolor: '#eef0f4',
    px: '9px',
    py: '2px',
    fontSize: '11px',
    fontWeight: 500,
    color: '#464c5e',
  },
  queuedStatusRow: {
    mt: '5px',
    display: 'flex',
    justifyContent: 'flex-end',
    pr: '2px',
  },
  queuedStatus: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '4px',
    fontSize: '11px',
    fontWeight: 500,
    lineHeight: 1.4,
    color: '#858b9c',
  },

  // Markdown answer
  markdown: {
    minWidth: 0,
    maxWidth: '100%',
    fontSize: '14px',
    lineHeight: 1.75,
    color: '#18181a',
    '& > *:first-of-type': { mt: 0 },
    '& > *:last-of-type': { mb: 0 },
    '& p': { my: '8px', overflowWrap: 'anywhere' },
    '& h1': { mt: '16px', mb: '8px', fontSize: '18px', fontWeight: 600 },
    '& h2': { mt: '16px', mb: '8px', fontSize: '16px', fontWeight: 600 },
    '& h3': { mt: '14px', mb: '6px', fontSize: '15px', fontWeight: 600 },
    '& h4': { mt: '12px', mb: '6px', fontSize: '14px', fontWeight: 600 },
    '& ul': { my: '8px', pl: '22px', listStyle: 'disc' },
    '& ol': { my: '8px', pl: '22px', listStyle: 'decimal' },
    '& li': { my: '3px' },
    '& a': { color: '#0b6cf5', textDecoration: 'underline', textUnderlineOffset: '2px' },
    '& .md-link-label': { color: '#0b6cf5', textDecoration: 'underline', textUnderlineOffset: '2px' },
    '& blockquote': { my: '10px', borderLeft: '3px solid #dfe5f2', pl: '12px', color: '#5b6273' },
    '& hr': { my: '12px', border: 0, borderTop: '1px solid #e3e7f1' },
    '& strong': { fontWeight: 600 },
    '& code': {
      borderRadius: '5px',
      bgcolor: '#f1f2f5',
      px: '5px',
      py: '1px',
      fontFamily: 'monospace',
      fontSize: '12.5px',
    },
    '& .code-block-vscode': { my: '10px' },
  },
  mdTableScroll: {
    my: '10px',
    maxWidth: '100%',
    overflowX: 'auto',
  },
  mdTable: {
    width: '100%',
    borderCollapse: 'collapse',
    fontSize: '13px',
    '& th': {
      border: '1px solid #e3e7f1',
      bgcolor: '#f7f8fa',
      px: '10px',
      py: '6px',
      fontWeight: 600,
    },
    '& td': {
      border: '1px solid #e3e7f1',
      px: '10px',
      py: '6px',
    },
  },

  // Execution record trace panel
  traceWrap: {
    mb: '10px',
    minWidth: 0,
  },
  traceSummary: {
    display: 'inline-flex',
    cursor: 'pointer',
    alignItems: 'center',
    gap: '7px',
    borderWidth: 0,
    bgcolor: 'transparent',
    p: 0,
    fontSize: '13px',
    fontWeight: 600,
    lineHeight: 1.5,
    color: '#464c5e',
    transition: 'background-color 0.15s, color 0.15s',
    '&:hover': { color: '#18181a' },
  },
  traceSummaryRunning: {
    color: '#18181a',
  },
  traceSummaryFailed: {
    color: '#d20b0b',
  },
  traceIcon: {
    display: 'inline-flex',
    width: '18px',
    height: '18px',
    flexShrink: 0,
    alignItems: 'center',
    justifyContent: 'center',
    color: '#858b9c',
    '& > svg': { display: 'block', width: '14px', height: '14px' },
  },
  traceChevron: {
    transition: 'transform 0.15s',
  },
  traceChevronExpanded: {
    transform: 'rotate(90deg)',
  },
  traceDetails: {
    mt: '8px',
    display: 'grid',
    gap: '8px',
    borderLeft: '1.5px solid #eef0f4',
    pl: '14px',
  },
  traceLine: {
    display: 'grid',
    gridTemplateColumns: '18px minmax(0,1fr)',
    alignItems: 'start',
    gap: '8px',
  },
  traceLineContent: {
    display: 'grid',
    gridTemplateColumns: 'minmax(0,1fr)',
    minWidth: 0,
    gap: '4px',
  },
  traceLineText: {
    fontSize: '13px',
    lineHeight: 1.5,
    color: '#464c5e',
    overflowWrap: 'anywhere',
  },
  traceFlowText: {},
  traceLineTextFailed: {
    color: '#d20b0b',
  },
  traceLineDetail: {
    fontSize: '12px',
    lineHeight: 1.5,
    color: '#858b9c',
    overflowWrap: 'anywhere',
  },
  traceCodeSummary: {
    cursor: 'pointer',
    fontSize: '12px',
    fontWeight: 500,
    color: '#757f9c',
    '&:hover': { color: '#18181a' },
  },
  traceCodeDetails: {
    display: 'block',
    minWidth: 0,
    maxWidth: '100%',
    overflow: 'hidden',
  },
  traceCodeBlock: {
    mt: '6px',
    maxHeight: '420px',
    width: '100%',
    maxWidth: '100%',
    overflow: 'auto',
    overscrollBehavior: 'contain',
  },

  // Citations
  citations: {
    mt: '12px',
    display: 'grid',
    minWidth: 0,
    maxWidth: '100%',
    gap: '8px',
    overflow: 'hidden',
    borderTop: '1px solid #f0f1f4',
    pt: '10px',
  },
  citationHeading: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    fontSize: '12px',
    fontWeight: 600,
    color: '#757f9c',
  },
  citationList: {
    display: 'flex',
    minWidth: 0,
    maxWidth: '100%',
    flexWrap: 'wrap',
    gap: '6px',
    overflow: 'hidden',
  },
  citationChip: {
    display: 'inline-flex',
    minWidth: 0,
    maxWidth: '100%',
    alignItems: 'center',
    gap: '6px',
    overflow: 'hidden',
    borderRadius: '8px',
    border: '1px solid #e3e7f1',
    bgcolor: '#fafbfc',
    px: '9px',
    py: '5px',
    textAlign: 'left',
    fontSize: '12px',
    color: '#464c5e',
    transition: 'background-color 0.15s, color 0.15s',
    '&:hover': { borderColor: '#c9d2e4', bgcolor: 'background.paper' },
  },
  citationIndex: {
    flexShrink: 0,
    fontWeight: 600,
    color: '#18181a',
  },
  citationTitle: {
    minWidth: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },

  // Message attachments (in-bubble)
  attachmentList: {
    mt: '10px',
    display: 'grid',
    gap: '8px',
  },
  attachmentCard: {
    display: 'grid',
    minHeight: '46px',
    width: 'min(280px,100%)',
    gridTemplateColumns: '36px minmax(0,1fr)',
    alignItems: 'center',
    gap: '10px',
    borderRadius: '10px',
    border: '1px solid #e3e7f1',
    bgcolor: '#fafbfc',
    p: '7px',
  },
  attachmentImg: {
    width: '36px',
    height: '36px',
    borderRadius: '8px',
    objectFit: 'cover',
  },
  attachmentFileIcon: {
    display: 'inline-grid',
    width: '36px',
    height: '36px',
    placeItems: 'center',
    borderRadius: '8px',
    bgcolor: '#eef0f4',
    color: '#464c5e',
  },
  attachmentCopy: {
    display: 'grid',
    minWidth: 0,
    gap: '1px',
  },
  attachmentName: {
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    fontSize: '12px',
    fontWeight: 500,
    color: '#18181a',
  },
  attachmentMeta: {
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    fontSize: '11px',
    color: '#858b9c',
  },

  // Feedback actions
  feedback: {
    mt: '10px',
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
  },
  feedbackBtn: {
    display: 'inline-grid',
    width: '28px',
    height: '28px',
    placeItems: 'center',
    borderRadius: '8px',
    borderWidth: 0,
    bgcolor: 'transparent',
    p: 0,
    color: '#a2a8b8',
    transition: 'background-color 0.15s, color 0.15s',
    '&:hover': { bgcolor: '#f1f2f5', color: '#18181a' },
  },
  feedbackBtnActive: {
    bgcolor: '#eef0f4',
    color: '#18181a',
  },
  feedbackBtnDislikeActive: {
    bgcolor: '#fce7e7',
    color: '#d20b0b',
    '&:hover': { bgcolor: '#fce7e7', color: '#d20b0b' },
  },

  // Empty state (Hello {name})
  empty: {
    mx: 'auto',
    display: 'flex',
    width: '100%',
    maxWidth: '640px',
    flexDirection: 'column',
    gap: '16px',
    pt: '8vh',
  },
  emptyGreetingCard: {
    display: 'flex',
    width: '100%',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    borderRadius: '20px',
    bgcolor: '#f6f6f6',
    pl: '8px',
    pr: '16px',
  },
  emptyTitle: {
    fontSize: '36px',
    fontWeight: 600,
    lineHeight: 1,
    color: '#18181a',
  },
  emptySubtitle: {
    fontSize: '18px',
    fontWeight: 500,
    color: '#464c5e',
  },
  emptyCard: {
    display: 'flex',
    width: '100%',
    alignItems: 'stretch',
    gap: '8px',
    borderRadius: '20px',
    bgcolor: '#f6f6f6',
    p: '16px',
  },
  emptyRole: {
    display: '-webkit-box',
    WebkitLineClamp: 2,
    WebkitBoxOrient: 'vertical',
    overflow: 'hidden',
    fontSize: '12px',
    textTransform: 'capitalize',
    lineHeight: 1.5,
    color: '#757f9c',
  },
  emptyTags: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: '10px',
    '& > span': {
      borderRadius: '10px',
      border: '0.5px solid #e3e7f1',
      px: '10px',
      py: '4px',
      fontSize: '10px',
      textTransform: 'capitalize',
      color: '#757f9c',
    },
  },
  emptyStatCell: {
    display: 'flex',
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'center',
    gap: '4px',
    border: '0.5px solid #e3e7f1',
    px: '20px',
    py: '8px',
    textTransform: 'capitalize',
    color: '#464c5e',
    '&:first-of-type': { borderTopLeftRadius: '14px', borderBottomLeftRadius: '14px' },
    '&:last-of-type': { borderTopRightRadius: '14px', borderBottomRightRadius: '14px' },
    '&:not(:first-of-type)': { ml: '-0.5px' },
  },

  // Composer
  inputShell: {
    flexShrink: 0,
    px: '24px',
    pb: '20px',
    pt: '6px',
  },
  composerStage: {
    position: 'relative',
    mx: 'auto',
    width: '100%',
    maxWidth: '820px',
  },
  composerAvatar: {
    position: 'absolute',
    bottom: '100%',
    left: '16px',
    zIndex: 10,
    mb: '2px',
    width: '44px',
    height: '44px',
    flexShrink: 0,
    overflow: 'hidden',
  },
  composerForm: {
    position: 'relative',
    display: 'flex',
    minWidth: 0,
    flex: 1,
    flexDirection: 'column',
    gap: '10px',
    borderRadius: '14px',
    border: '0.5px solid #18181a',
    bgcolor: 'background.paper',
    p: '12px',
    boxShadow: '0 6px 24px rgba(24,24,26,0.08)',
    transition: 'background-color 0.15s, color 0.15s',
  },
  composerFormDrag: {
    borderStyle: 'dashed',
    borderColor: '#0b6cf5',
    bgcolor: '#f5f9ff',
  },
  composerDropHint: {
    pointerEvents: 'none',
    position: 'absolute',
    inset: 0,
    zIndex: 2,
    display: 'grid',
    placeItems: 'center',
    borderRadius: '14px',
    bgcolor: 'rgba(255,255,255,0.85)',
    fontSize: '14px',
    fontWeight: 500,
    color: '#18181a',
    backdropFilter: 'blur(4px)',
  },
  composerTextarea: {
    minHeight: '48px',
    maxHeight: '200px',
    width: '100%',
    resize: 'none',
    borderWidth: 0,
    bgcolor: 'transparent',
    px: '4px',
    py: '2px',
    fontSize: '14px',
    lineHeight: 1.7,
    color: '#18181a',
    boxShadow: 'none',
    outline: 'none',
    '&::placeholder': { color: '#b3b8c4' },
    '&:focus-visible': { boxShadow: 'none' },
  },
  composerAttachments: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '8px',
  },
  composerAttachmentChip: {
    display: 'inline-flex',
    maxWidth: '240px',
    alignItems: 'center',
    gap: '7px',
    borderRadius: '10px',
    border: '1px solid #e3e7f1',
    bgcolor: '#fafbfc',
    py: '5px',
    pl: '7px',
    pr: '6px',
    fontSize: '12px',
    color: '#464c5e',
  },
  composerAttachmentError: {
    borderColor: '#f38989',
    bgcolor: '#fce7e7',
    color: '#d20b0b',
  },
  composerAttachmentImg: {
    width: '24px',
    height: '24px',
    borderRadius: '6px',
    objectFit: 'cover',
  },
  composerAttachmentCopy: {
    display: 'grid',
    minWidth: 0,
    gap: '1px',
  },
  composerAttachmentName: {
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    fontSize: '12px',
    fontWeight: 500,
    color: '#18181a',
  },
  composerAttachmentStatus: {
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    fontSize: '11px',
    color: '#858b9c',
  },
  composerAttachmentRemove: {
    display: 'inline-grid',
    width: '18px',
    height: '18px',
    flexShrink: 0,
    placeItems: 'center',
    borderRadius: '9999px',
    borderWidth: 0,
    bgcolor: 'transparent',
    p: 0,
    fontSize: '15px',
    lineHeight: 1,
    color: '#a2a8b8',
    '&:hover': { color: '#18181a' },
  },
  composerToolbar: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '10px',
  },
  composerContextRow: {
    display: 'flex',
    minWidth: 0,
    alignItems: 'center',
    gap: '8px',
  },
  composerActionsRow: {
    display: 'flex',
    flexShrink: 0,
    alignItems: 'center',
    gap: '8px',
  },
  composerPlusBtn: {
    display: 'inline-grid',
    width: '32px',
    height: '32px',
    placeItems: 'center',
    borderRadius: '9px',
    border: '1px solid #e3e7f1',
    bgcolor: 'background.paper',
    p: 0,
    color: '#464c5e',
    transition: 'background-color 0.15s, color 0.15s',
    '&:hover': { borderColor: '#c9d2e4', color: '#18181a' },
    '&:disabled': { cursor: 'not-allowed', opacity: 0.45 },
  },
  composerIntentChip: {
    display: 'inline-flex',
    cursor: 'pointer',
    alignItems: 'center',
    gap: '5px',
    borderRadius: '9999px',
    border: '1px solid #e3e7f1',
    bgcolor: '#f4f5f7',
    py: '4px',
    pl: '6px',
    pr: '10px',
    fontSize: '12px',
    fontWeight: 500,
    color: '#464c5e',
    transition: 'background-color 0.15s, color 0.15s',
    '&:hover': { borderColor: '#c9d2e4', color: '#18181a' },
    '&:focus-visible': { outline: 'none', boxShadow: '0 0 0 1px #ffffff, 0 0 0 3px #c9d2e4' },
  },
  composerHint: {
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    fontSize: '11px',
    color: '#b3b8c4',
    '@media (max-width:560px)': { display: 'none' },
  },
  composerModelBtn: {
    display: 'inline-flex',
    height: '32px',
    maxWidth: '200px',
    alignItems: 'center',
    gap: '5px',
    borderRadius: '9px',
    border: '1px solid #e3e7f1',
    bgcolor: 'background.paper',
    px: '12px',
    fontSize: '12px',
    fontWeight: 400,
    color: '#757f9c',
    boxShadow: 'none',
    transition: 'background-color 0.15s, color 0.15s',
    '&:hover': { borderColor: '#c9d2e4', color: '#18181a' },
    '&:disabled': { cursor: 'not-allowed', opacity: 0.45 },
    '&[aria-expanded="true"]': { borderColor: '#c9d2e4', color: '#18181a' },
    '& > span:first-of-type': {
      minWidth: 0,
      overflow: 'hidden',
      textOverflow: 'ellipsis',
      whiteSpace: 'nowrap',
    },
  },
  composerSendBtn: {
    display: 'inline-grid',
    width: '36px',
    height: '36px',
    placeItems: 'center',
    borderRadius: '10px',
    bgcolor: '#18181a',
    p: 0,
    color: '#fff',
    transition: 'background-color 0.15s, color 0.15s',
    '&:hover': { bgcolor: '#303030' },
    '&:disabled': { cursor: 'not-allowed', opacity: 0.40 },
  },
  composerStopBtn: {
    bgcolor: '#d20b0b',
    '&:hover': { bgcolor: '#b40a0a' },
  },
  menuContent: {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
    borderRadius: '14px',
    borderWidth: 0,
    bgcolor: 'background.paper',
    p: '6px',
    boxShadow: '0px 16px 15px rgba(0,0,0,0.1)',
    '--accent': '#F6F6F6',
    '--accent-foreground': '#18181A',
  },
  menuItem: {
    height: '36px',
    cursor: 'pointer',
    gap: '8px',
    borderRadius: '10px',
    px: '12px',
    fontSize: '14px',
    color: '#464C5E',
  },
  modelMenuItem: {
    display: 'flex',
    height: 'auto',
    cursor: 'pointer',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '16px',
    borderRadius: '10px',
    px: '12px',
    py: '8px',
    color: '#464C5E',
  },
  modelMenuCopy: {
    display: 'grid',
    minWidth: 0,
    gap: '1px',
  },
  modelMenuName: {
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    fontSize: '13px',
    fontWeight: 500,
    color: '#18181a',
  },
  modelMenuDetail: {
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    fontSize: '11px',
    color: '#858b9c',
  },

  // Scheduled task draft card
  draftCard: {
    mt: '12px',
    display: 'grid',
    gap: '12px',
    borderRadius: '14px',
    border: '0.5px solid #e3e7f1',
    bgcolor: '#fafbfc',
    p: '14px',
  },
  draftCardCreated: {
    borderColor: '#96d9b0',
    bgcolor: '#f2fbf5',
  },
  draftHeader: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: '12px',
  },
  draftIdentity: {
    display: 'flex',
    minWidth: 0,
    alignItems: 'center',
    gap: '10px',
  },
  draftIcon: {
    display: 'inline-grid',
    width: '34px',
    height: '34px',
    flexShrink: 0,
    placeItems: 'center',
    borderRadius: '10px',
    bgcolor: '#eef0f4',
    color: '#464c5e',
  },
  draftKicker: {
    fontSize: '11px',
    fontWeight: 500,
    color: '#858b9c',
  },
  draftTitle: {
    fontSize: '14px',
    fontWeight: 600,
    color: '#18181a',
  },
  draftTopActions: {
    display: 'flex',
    flexShrink: 0,
    alignItems: 'center',
    gap: '6px',
  },
  draftCreatedBadge: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '4px',
    borderRadius: '9999px',
    bgcolor: '#e9f7ef',
    px: '10px',
    py: '3px',
    fontSize: '12px',
    fontWeight: 500,
    color: '#018434',
  },
  draftMetaGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, minmax(0,1fr))',
    gap: '10px',
    '@media (max-width:520px)': { gridTemplateColumns: 'repeat(1, minmax(0,1fr))' },
  },
  draftMetaItem: {
    display: 'grid',
    gap: '3px',
    borderRadius: '10px',
    bgcolor: 'background.paper',
    px: '10px',
    py: '8px',
    '& > span': { fontSize: '11px', color: '#858b9c' },
    '& > strong': { fontSize: '13px', fontWeight: 500, color: '#18181a' },
  },
  draftPrompt: {
    display: 'grid',
    gap: '4px',
    '& > span': { fontSize: '11px', color: '#858b9c' },
    '& > p': { fontSize: '13px', lineHeight: 1.6, color: '#464c5e' },
  },
  draftEditor: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, minmax(0,1fr))',
    gap: '10px',
    '@media (max-width:520px)': { gridTemplateColumns: 'repeat(1, minmax(0,1fr))' },
    '& label': { display: 'grid', gap: '5px' },
    '& label > span': { fontSize: '12px', color: '#757f9c' },
  },
  draftEditorFull: {
    gridColumn: '1 / -1',
  },
  draftFooter: {
    display: 'flex',
    justifyContent: 'flex-end',
    gap: '8px',
  },

  // Dialogs (handoff inbox + citation detail + rename)
  handoffList: {
    display: 'grid',
    maxHeight: '60vh',
    gap: '14px',
    overflowY: 'auto',
  },
  handoffCard: {
    display: 'grid',
    gap: '12px',
    borderRadius: '14px',
    border: '1px solid #e3e7f1',
    bgcolor: '#fafbfc',
    p: '16px',
  },
  handoffHead: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    '& strong': { display: 'block', fontSize: '14px', fontWeight: 600, color: '#18181a' },
    '& span': { fontSize: '12px', color: '#858b9c' },
  },
  handoffBlock: {
    display: 'grid',
    gap: '4px',
    '& > span': { fontSize: '12px', fontWeight: 500, color: '#757f9c' },
    '& > p': { fontSize: '13px', lineHeight: 1.6, color: '#464c5e' },
  },
  handoffActions: {
    display: 'flex',
    justifyContent: 'flex-end',
    gap: '8px',
  },
  handoffEmpty: {
    py: '36px',
    textAlign: 'center',
    fontSize: '13px',
    color: '#858b9c',
  },

  citationDetail: {
    display: 'grid',
    width: '100%',
    minWidth: 0,
    gap: '14px',
  },
  citationDetailEyebrow: {
    fontSize: '12px',
    fontWeight: 500,
    color: '#858b9c',
  },
  citationDetailTitle: {
    fontSize: '18px',
    fontWeight: 600,
    color: '#18181a',
  },
  citationDetailSection: {
    display: 'grid',
    width: '100%',
    minWidth: 0,
    gap: '5px',
    '& > span': { fontSize: '12px', fontWeight: 500, color: '#757f9c' },
    '& > p': { fontSize: '13px', lineHeight: 1.7, color: '#464c5e' },
  },
  citationDetailQuote: {
    m: 0,
    maxHeight: 'min(52vh,520px)',
    overflowY: 'auto',
    overscrollBehavior: 'contain',
    borderRadius: '10px',
    borderLeft: '3px solid #e3e7f1',
    bgcolor: '#fafbfc',
    px: '12px',
    py: '8px',
    fontSize: '13px',
    lineHeight: 1.7,
    whiteSpace: 'pre-wrap',
    overflowWrap: 'anywhere',
    color: '#464c5e',
  },
  citationDetailMarkdown: {
    maxHeight: 'min(52vh,520px)',
    width: '100%',
    minWidth: 0,
    maxWidth: '100%',
    overflowY: 'auto',
    overscrollBehavior: 'contain',
    borderRadius: '10px',
    borderLeft: '3px solid #e3e7f1',
    bgcolor: '#fafbfc',
    px: '12px',
    py: '8px',
    '& > div': {
      width: '100%',
      minWidth: 0,
      maxWidth: 'none',
      fontSize: '13px',
      lineHeight: 1.7,
      color: '#464c5e',
    },
    '& h1': { fontSize: '16px' },
    '& h2': { fontSize: '15px' },
    '& h3': { fontSize: '14px' },
    '& h4': { fontSize: '13px' },
    '& p': { overflowWrap: 'anywhere' },
    '& li': { overflowWrap: 'anywhere' },
    '& code': { overflowWrap: 'anywhere' },
    '& a': { overflowWrap: 'anywhere' },
  },
  citationDetailGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, minmax(0,1fr))',
    gap: '12px',
    '@media (max-width:520px)': { gridTemplateColumns: 'repeat(1, minmax(0,1fr))' },
    '& > div': { display: 'grid', gap: '3px' },
    '& span': { fontSize: '11px', color: '#858b9c' },
    '& strong': { fontSize: '13px', fontWeight: 500, color: '#18181a' },
  },
  citationDetailNote: {
    fontSize: '12px',
    lineHeight: 1.6,
    color: '#858b9c',
  },

  debugPanel: {
    mx: 'auto',
    mt: '16px',
    maxWidth: '820px',
    overflow: 'auto',
    borderRadius: '10px',
    bgcolor: '#1e1e1e',
    p: '12px',
    fontSize: '12px',
    color: '#d4d4d4',
  },
} satisfies Record<string, SxProps<Theme>>;

// Helper functions mirroring the old chatRowClass / chatBubbleClass.
export function chatRowSx(role: 'user' | 'assistant' | 'system' | 'tool'): SxProps<Theme> {
  return [
    chatTokens.messageRowBase,
    role === 'user' ? chatTokens.messageRowUser : chatTokens.messageRowAssistant,
  ];
}

export function chatBubbleSx(
  role: 'user' | 'assistant' | 'system' | 'tool',
  isError?: boolean,
): SxProps<Theme> {
  return [
    chatTokens.bubbleBase,
    role === 'user' ? chatTokens.bubbleUser : chatTokens.bubbleAssistant,
    ...(isError ? [chatTokens.bubbleError] : []),
  ];
}
