// Re-exports channel provider Zod schemas defined in zod-schema.providers-core.ts.
// openclaw splits channel provider schemas across providers-core/providers-googlechat/
// providers-whatsapp; this file aggregates the core provider schemas for convenience.
export {
  TelegramTopicSchema,
  TelegramGroupSchema,
  TelegramDirectSchema,
  TelegramAccountSchemaBase,
  TelegramAccountSchema,
  TelegramConfigSchema,
  DiscordDmSchema,
  DiscordThreadSchema,
  DiscordGuildChannelSchema,
  DiscordGuildSchema,
  DiscordAccountSchema,
  DiscordConfigSchema,
  SlackDmSchema,
  SlackChannelSchema,
  SlackThreadSchema,
  SlackSocketModeSchema,
  SlackRelaySchema,
  SlackAccountSchema,
  SlackConfigSchema,
  SignalAccountSchemaBase,
  SignalConfigSchema,
  IrcGroupSchema,
  IrcNickServSchema,
  IrcAccountSchemaBase,
  IrcAccountSchema,
  IrcConfigSchema,
  IMessageAccountSchemaBase,
  IMessageConfigSchema,
  MSTeamsChannelSchema,
  MSTeamsTeamSchema,
  MSTeamsConfigSchema,
} from "./zod-schema.providers-core.js";
