/**
 * StaffDeck icon set. Re-exports `lucide-react` icons used across the
 * StaffDeck UI so consumers have a single import surface. Additional icons
 * can be added here as the UI grows.
 */
export {
  Activity,
  AlertCircle,
  AlertTriangle,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Bell,
  Bot,
  Brain,
  Briefcase,
  Building2,
  Calendar,
  CalendarClock,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsUpDown,
  Circle,
  Clock,
  Copy,
  Database,
  Delete,
  Download,
  Edit,
  Edit2,
  Edit3,
  ExternalLink,
  Eye,
  EyeOff,
  File,
  FileText,
  Filter,
  Folder,
  Globe,
  HelpCircle,
  History,
  Home,
  Image,
  Inbox,
  Info,
  Key,
  Languages,
  LayoutDashboard,
  Link2,
  ListChecks,
  Loader2,
  Lock,
  LogIn,
  LogOut,
  type LucideIcon,
  type LucideProps,
  Mail,
  MessageCircle,
  MessageSquare,
  MessagesSquare,
  MoreHorizontal,
  MoreVertical,
  Pencil,
  Play,
  Plus,
  RefreshCw,
  Save,
  Search,
  Send,
  Server,
  Settings,
  Settings2,
  Share2,
  Sparkles,
  Star,
  StopCircle,
  Trash,
  Trash2,
  Upload,
  User,
  UserPlus,
  Users,
  Wrench,
  X,
  Zap,
} from 'lucide-react'

// Antd-style aliases kept for compatibility with components that import these
// names. Prefer the lucide-react names above for new code.
export {
  Check as CheckOutlined,
  Upload as UploadOutlined,
  User as IdcardOutlined,
} from 'lucide-react'
