/** 各 AI 提供商 API Key 申请/管理页面 URL */
export const PROVIDER_API_KEY_URLS: Record<string, string> = {
  openai: 'https://platform.openai.com/api-keys',
  anthropic: 'https://console.anthropic.com/settings/keys',
  google: 'https://aistudio.google.com/apikey',
  deepseek: 'https://platform.deepseek.com/api_keys',
  moonshot: 'https://platform.moonshot.cn/console/api-keys',
  zhipu: 'https://open.bigmodel.cn/usercenter/apikeys',
  qwen: 'https://dashscope.console.aliyun.com/apiKey',
  baichuan: 'https://platform.baichuan-ai.com/console/apikey',
  minimax: 'https://platform.minimaxi.com/user-center/basic-information/interface-key',
  doubao: 'https://console.volcengine.com/ark/region:ark+cn-beijing/apiKey',
  xai: 'https://console.x.ai/',
  groq: 'https://console.groq.com/keys',
  together: 'https://api.together.xyz/settings/api-keys',
  perplexity: 'https://www.perplexity.ai/settings/api',
  mistral: 'https://console.mistral.ai/api-keys/',
  cohere: 'https://dashboard.cohere.com/api-keys',
  ai21: 'https://studio.ai21.com/account/api-key',
  replicate: 'https://replicate.com/account/api-tokens',
  openrouter: 'https://openrouter.ai/keys',
  siliconflow: 'https://cloud.siliconflow.cn/account/ak',
  deepinfra: 'https://deepinfra.com/dash/api_keys',
  fireworks: 'https://fireworks.ai/account/api-keys',
  voyage: 'https://dash.voyageai.com/api-keys',
  jina: 'https://jina.ai/embeddings/',
  ollama: 'https://ollama.com/',
  custom: '',
};
