export function getMarkdownTemplate(): string {
  return `# {{skillName}}

{{description}}

**版本**: {{version}}
{{#if author}}**作者**: {{author}}
{{/if}}

{{#if tools.length}}## 工具函数

{{#each tools}}### {{name}}

{{description}}

{{#if parameters.length}}**参数**:

| 参数名 | 类型 | 必填 | 描述 |
| ------ | ---- | ---- | ---- |
{{#each parameters}}| {{name}} | {{type}} | {{#if required}}是{{else}}否{{/if}} | {{description}} |
{{/each}}

{{/if}}**返回类型**: \`{{returnType}}\`

{{/each}}{{/if}}

{{#if commands.length}}## 命令

{{#each commands}}### \`{{command}}\`

{{description}}

{{#if examples.length}}**示例**:

{{#each examples}}\`\`\`
{{.}}
\`\`\`

{{/each}}{{/if}}{{/each}}{{/if}}

{{#if examples.length}}## 使用示例

{{#each examples}}### {{title}}

**输入**:

\`\`\`
{{input}}
\`\`\`

{{#if output}}**输出**:

\`\`\`
{{output}}
\`\`\`

{{/if}}{{/each}}{{/if}}

{{#if apiReference.endpoints.length}}## API 参考

| 方法 | 路径 | 描述 |
| ---- | ---- | ---- |
{{#each apiReference.endpoints}}| {{method}} | {{path}} | {{description}} |
{{/each}}

{{/if}}`;
}

export function getHtmlTemplate(): string {
  return `<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{{skillName}} - 技能文档</title>
  <style>
    :root {
      --primary-color: #1a1a2e;
      --secondary-color: #16213e;
      --accent-color: #e94560;
      --light-gray: #f5f5f5;
      --border-color: #eee;
      --text-muted: #666;
    }

    * {
      box-sizing: border-box;
      margin: 0;
      padding: 0;
    }

    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
      max-width: 900px;
      margin: 0 auto;
      padding: 40px 20px;
      color: var(--primary-color);
      line-height: 1.6;
    }

    h1 {
      color: var(--primary-color);
      font-size: 2em;
      margin-bottom: 10px;
      border-bottom: 3px solid var(--accent-color);
      padding-bottom: 10px;
    }

    h2 {
      color: var(--secondary-color);
      font-size: 1.5em;
      margin: 30px 0 15px;
      padding-bottom: 5px;
      border-bottom: 2px solid var(--border-color);
    }

    h3 {
      color: var(--secondary-color);
      font-size: 1.2em;
      margin: 20px 0 10px;
    }

    p {
      margin-bottom: 15px;
    }

    .metadata {
      margin: 15px 0;
      padding: 10px 15px;
      background-color: var(--light-gray);
      border-radius: 5px;
    }

    .metadata span {
      margin-right: 25px;
      color: var(--text-muted);
    }

    table {
      width: 100%;
      border-collapse: collapse;
      margin: 15px 0;
      font-size: 0.9em;
    }

    th, td {
      border: 1px solid var(--border-color);
      padding: 10px 12px;
      text-align: left;
    }

    th {
      background-color: var(--light-gray);
      font-weight: 600;
    }

    tr:nth-child(even) {
      background-color: #fafafa;
    }

    pre {
      background-color: #f8f9fa;
      padding: 20px;
      border-radius: 8px;
      overflow-x: auto;
      font-family: 'Monaco', 'Menlo', 'Ubuntu Mono', monospace;
      font-size: 0.85em;
      line-height: 1.5;
      margin: 10px 0;
    }

    code {
      background-color: var(--light-gray);
      padding: 2px 6px;
      border-radius: 3px;
      font-family: 'Monaco', 'Menlo', 'Ubuntu Mono', monospace;
      font-size: 0.9em;
    }

    .tool, .example {
      margin-bottom: 25px;
      padding: 20px;
      border: 1px solid var(--border-color);
      border-radius: 8px;
      background-color: #fff;
    }

    .tool h3, .example h3 {
      margin-top: 0;
      color: var(--accent-color);
    }

    .footer {
      margin-top: 50px;
      padding-top: 20px;
      border-top: 1px solid var(--border-color);
      text-align: center;
      color: var(--text-muted);
      font-size: 0.85em;
    }
  </style>
</head>
<body>
{{content}}
<div class="footer">
  Generated by Cross-WMS Docs Generator
</div>
</body>
</html>`;
}

export function applyTemplate(template: string, data: Record<string, any>): string {
  let result = template;

  result = result.replace(/\{\{(\w+)\}\}/g, (match, key) => {
    return data[key] !== undefined ? String(data[key]) : '';
  });

  result = result.replace(/\{\{#if (\w+)\}\}([\s\S]*?)\{\{\/if\}\}/g, (match, key, content) => {
    const value = data[key];
    if (Array.isArray(value)) {
      return value.length > 0 ? content : '';
    }
    return value ? content : '';
  });

  result = result.replace(/\{\{#each (\w+)\}\}([\s\S]*?)\{\{\/each\}\}/g, (match, key, content) => {
    const array = data[key] as any[];
    if (!Array.isArray(array)) {
      return '';
    }
    return array.map((item) => {
      if (typeof item === 'object' && item !== null) {
        return applyTemplate(content, item as Record<string, any>);
      }
      return content.replace(/\{\{\.\}\}/g, String(item));
    }).join('');
  });

  return result;
}
